Repository mui/mui-x, pull requests merged in 2020-07, with the labels that each got.

#68 Add doc comments to model
  README.md
  packages/grid/x-grid-modules/package.json
  packages/grid/x-grid-modules/src/gridComponent.tsx
  packages/grid/x-grid-modules/src/gridComponentProps.ts
  packages/grid/x-grid-modules/src/models/api/columnApi.ts
  packages/grid/x-grid-modules/src/models/api/gridApi.ts
  packages/grid/x-grid-modules/src/models/api/gridApiRef.ts
  packages/grid/x-grid-modules/src/models/api/paginationApi.ts
  packages/grid/x-grid-modules/src/models/api/rowApi.ts
  packages/grid/x-grid-modules/src/models/api/selectionApi.ts
  packages/grid/x-grid-modules/src/models/api/sortApi.ts
  packages/grid/x-grid-modules/src/models/api/virtualizationApi.ts
  packages/grid/x-grid-modules/src/models/cellClass.ts
  packages/grid/x-grid-modules/src/models/colDef/colDef.ts
  packages/grid/x-grid-modules/src/models/containerProps.ts
  packages/grid/x-grid-modules/src/models/elementSize.ts
  packages/grid/x-grid-modules/src/models/gridComponentOverridesProp.tsx
  packages/grid/x-grid-modules/src/models/gridOptions.tsx
  packages/grid/x-grid-modules/src/models/params/cellClickedParams.ts
  packages/grid/x-grid-modules/src/models/params/cellParams.ts
  packages/grid/x-grid-modules/src/models/params/colParams.ts
  packages/grid/x-grid-modules/src/models/params/columnHeaderClickedParams.ts
  packages/grid/x-grid-modules/src/models/params/columnSortedParams.ts
  packages/grid/x-grid-modules/src/models/params/componentParams.ts
  packages/grid/x-grid-modules/src/models/params/pageChangedParams.ts
  packages/grid/x-grid-modules/src/models/params/rowClickedParams.ts
  packages/grid/x-grid-modules/src/models/params/rowSelectedParams.ts
  packages/grid/x-grid-modules/src/models/params/selectionChangedParams.ts
  packages/grid/x-grid-modules/src/models/renderContextProps.ts
  packages/grid/x-grid-modules/src/models/rows.ts
  packages/grid/x-grid-modules/src/models/sortModel.ts
  packages/storybook/src/documentation/pages/api.stories.mdx
  packages/storybook/src/documentation/pages/columns.stories.mdx
  packages/storybook/src/documentation/pages/demos/styling/styleCell.demo.tsx
  packages/storybook/src/documentation/pages/demos/styling/styleHeader.demo.tsx
  packages/storybook/src/documentation/pages/layout.stories.mdx
  packages/storybook/src/documentation/pages/overview.stories.mdx
  packages/storybook/src/documentation/pages/selection.stories.mdx
  packages/storybook/src/documentation/pages/styling.stories.mdx
Labels: docs

#105 [core] Use the classnames helper
  packages/demo-app/src/app/demos/grid/components/settings-panel.tsx
  packages/demo-app/src/app/demos/grid/real-data-grid.demo.tsx
  packages/grid/x-grid-modules/src/components/styled-wrappers/columns-container.tsx
  packages/grid/x-grid-modules/src/components/styled-wrappers/data-container.tsx
  packages/grid/x-grid-modules/src/components/styled-wrappers/footer.tsx
  packages/grid/x-grid-modules/src/components/styled-wrappers/grid-root.tsx
  packages/grid/x-grid-modules/src/components/styled-wrappers/window-overlay.tsx
  packages/grid/x-grid-modules/src/components/styled-wrappers/window.tsx
Labels: core

#104 [core] Batch small changes
  packages/demo-app/public/ag-logo.png
  packages/demo-app/public/aggrid.png
  packages/demo-app/public/android-icon-144x144.png
  packages/demo-app/public/android-icon-192x192.png
  packages/demo-app/public/android-icon-36x36.png
  packages/demo-app/public/android-icon-48x48.png
  packages/demo-app/public/android-icon-72x72.png
  packages/demo-app/public/android-icon-96x96.png
  packages/demo-app/public/apple-icon-114x114.png
  packages/demo-app/public/apple-icon-120x120.png
  packages/demo-app/public/apple-icon-144x144.png
  packages/demo-app/public/apple-icon-152x152.png
  packages/demo-app/public/apple-icon-180x180.png
  packages/demo-app/public/apple-icon-57x57.png
  packages/demo-app/public/apple-icon-60x60.png
  packages/demo-app/public/apple-icon-72x72.png
  packages/demo-app/public/apple-icon-76x76.png
  packages/demo-app/public/apple-icon-precomposed.png
  packages/demo-app/public/apple-icon.png
  packages/demo-app/public/favicon-16x16.png
  packages/demo-app/public/favicon-32x32.png
  packages/demo-app/public/favicon-96x96.png
  packages/demo-app/public/logo192.png
  packages/demo-app/public/logo512.png
  packages/demo-app/public/ms-icon-144x144.png
  packages/demo-app/public/ms-icon-150x150.png
  packages/demo-app/public/ms-icon-310x310.png
  packages/demo-app/public/ms-icon-70x70.png
  packages/demo-app/public/storybook.png
  packages/demo-app/src/app/demos/grid/components/settings-panel.tsx
  packages/demo-app/src/app/demos/theme/useTheme.ts
  packages/grid/x-grid-modules/lib/autosizer/index.js
  packages/grid/x-grid-modules/src/hooks/features/usePagination.ts
  packages/grid/x-grid-modules/src/hooks/utils/useLogger.ts
  packages/grid/x-grid-modules/src/hooks/virtualization/useVirtualColumns.ts
  packages/grid/x-grid-modules/src/hooks/virtualization/useVirtualRows.ts
  packages/grid/x-grid-modules/src/models/params/cellParams.ts
Labels: core

#106 [docs] Improve the JSDoc
  packages/grid/x-grid-modules/lib/autosizer/types.d.ts
  packages/grid/x-grid-modules/src/gridComponent.tsx
  packages/grid/x-grid-modules/src/gridComponentProps.ts
  packages/grid/x-grid-modules/src/models/api/apiRef.ts
  packages/grid/x-grid-modules/src/models/api/columnApi.ts
  packages/grid/x-grid-modules/src/models/api/gridApi.ts
  packages/grid/x-grid-modules/src/models/api/paginationApi.ts
  packages/grid/x-grid-modules/src/models/api/rowApi.ts
  packages/grid/x-grid-modules/src/models/api/selectionApi.ts
  packages/grid/x-grid-modules/src/models/api/sortApi.ts
  packages/grid/x-grid-modules/src/models/api/virtualizationApi.ts
  packages/grid/x-grid-modules/src/models/colDef/colDef.ts
  packages/grid/x-grid-modules/src/models/containerProps.ts
  packages/grid/x-grid-modules/src/models/elementSize.ts
  packages/grid/x-grid-modules/src/models/gridComponentOverridesProp.tsx
  packages/grid/x-grid-modules/src/models/gridOptions.tsx
  packages/grid/x-grid-modules/src/models/params/cellClickedParams.ts
  packages/grid/x-grid-modules/src/models/params/colParams.ts
  packages/grid/x-grid-modules/src/models/params/columnSortedParams.ts
  packages/grid/x-grid-modules/src/models/params/componentParams.ts
  packages/grid/x-grid-modules/src/models/params/pageChangedParams.ts
  packages/grid/x-grid-modules/src/models/params/rowClickedParams.ts
  packages/grid/x-grid-modules/src/models/params/rowSelectedParams.ts
  packages/grid/x-grid-modules/src/models/renderContextProps.ts
  packages/grid/x-grid-modules/src/models/rows.ts
  packages/grid/x-grid-modules/src/models/sortModel.ts
Labels: docs

#107 [test] Add yarn deduplicate step
  .circleci/config.yml
  package.json
  scripts/deduplicate.js
  yarn.lock
Labels: test

#117 [DataGrid] Set default logLevel to warn
  packages/grid/x-grid-modules/src/gridComponent.tsx
  packages/grid/x-grid-modules/src/models/gridOptions.tsx
Labels: component: DataGrid

#108 [test] Lint JSON
  .circleci/config.yml
  package.json
  scripts/jsonlint.js
Labels: test

#126 [DataGrid] Fix selection issue
  packages/grid/x-grid-modules/src/components/row-cells.tsx
  packages/storybook/integration/__image_snapshots__/static-stories-test-ts-snapshot-test-story-x-grid-tests-selection-multiple-select-with-checkbox-no-click-1-snap.png
  packages/storybook/integration/staticStories.test.ts
  packages/storybook/src/stories/grid-selection.stories.tsx
Labels: bug 🐛, component: DataGrid

#130 [DataGrid] Core api refactoring
  packages/grid/x-grid-modules/src/constants/eventsConstants.ts
  packages/grid/x-grid-modules/src/gridComponent.tsx
  packages/grid/x-grid-modules/src/hooks/features/useSorting.ts
  packages/grid/x-grid-modules/src/hooks/root/useApi.ts
  packages/grid/x-grid-modules/src/hooks/root/useColumns.ts
  packages/grid/x-grid-modules/src/hooks/root/useEvents.ts
  packages/grid/x-grid-modules/src/hooks/root/useRows.ts
  packages/grid/x-grid-modules/src/models/api/coreApi.ts
  packages/grid/x-grid-modules/src/models/api/eventsApi.ts
  packages/grid/x-grid-modules/src/models/api/gridApi.ts
  packages/grid/x-grid-modules/src/models/api/index.ts
  packages/grid/x-grid-modules/src/models/api/sortApi.ts
  packages/grid/x-grid-modules/src/models/gridOptions.tsx
  packages/grid/x-grid-modules/src/models/params/columnSortedParams.ts
  packages/grid/x-grid-modules/src/models/params/index.ts
  packages/grid/x-grid-modules/src/models/params/sortModelParams.ts
  packages/storybook/src/documentation/pages/demos/sorting/serverSorting.demo.tsx
  packages/storybook/src/documentation/pages/pagination.stories.mdx
  packages/storybook/src/documentation/pages/sorting.stories.mdx
  packages/storybook/src/stories/grid-events.stories.tsx
  packages/storybook/src/stories/grid-sorting.stories.tsx
  packages/storybook/src/stories/playground/data-grid.options.stories.tsx
  packages/storybook/src/stories/playground/options.stories.tsx
  packages/storybook/src/stories/playground/real-data-demo.stories.tsx
Labels: component: DataGrid
