Repository mui/mui-x, pull requests merged in 2020-08, with the labels that each got.

#135 [DataGrid] Fix SSR support
  packages/grid/x-grid-modules/src/hooks/utils/useLogger.ts
Labels: bug 🐛, component: DataGrid

#115 [test] Setup the e2e test suite (from main repo)
  .circleci/config.yml
  .eslintrc.js
  .gitignore
  .mocharc.js
  babel.config.js
  package.json
  packages/demo-app/package.json
  packages/grid/data-grid/package.json
  packages/grid/x-grid/rollup.config.js
  packages/grid/x-grid/test/XGrid.test.tsx
  packages/license/bin/license-gen-script.js
  packages/storybook/package.json
  test/karma.conf.js
  test/karma.tests.js
  test/utils/components.js
  test/utils/createClientRender.js
  test/utils/createDOM.d.ts
  test/utils/createDOM.js
  test/utils/createMount.js
  test/utils/createServerRender.js
  test/utils/createShallow.js
  test/utils/describeConformance.js
  test/utils/findOutermostIntrinsic.js
  test/utils/findOutermostIntrinsic.test.js
  test/utils/getClasses.js
  test/utils/index.js
  test/utils/init.d.ts
  test/utils/init.js
  test/utils/initMatchers.js
  test/utils/initMatchers.test.js
  test/utils/setup.js
  test/utils/until.js
  test/utils/until.test.js
  tsconfig.json
  webpackBaseConfig.js
  yarn.lock
Labels: test

#116 [storybook] Remove need for yarn-link
  babel.config.js
  netlify.toml
  packages/demo-app/src/app/demos/grid/real-data-grid.demo.tsx
  packages/grid/data-grid/tsconfig.json
  packages/grid/x-grid-data-generator/package.json
  packages/grid/x-grid-modules/src/hooks/utils/useLogger.ts
  packages/grid/x-grid-modules/tsconfig.json
  packages/grid/x-grid/tsconfig.json
  packages/license/src/encoding/base64.ts
  packages/storybook/.storybook/main.js
  packages/storybook/package.json
  packages/storybook/src/stories/grid-sorting.stories.tsx
  packages/storybook/src/stories/playground/real-data-demo.stories.tsx
  yarn.lock
Labels: docs

#136 [core] Batch small changes
  .eslintrc.js
  .gitignore
  packages/grid/data-grid/package.json
  packages/grid/x-grid-data-generator/package.json
  packages/grid/x-grid-modules/src/models/gridOptions.tsx
  packages/grid/x-grid/package.json
  packages/license/package.json
  packages/license/src/verifyLicense.ts
Labels: core

#134 [DataGrid] Add error handling
  packages/grid/x-grid-modules/src/components/error-boundary.tsx
  packages/grid/x-grid-modules/src/components/error-message.tsx
  packages/grid/x-grid-modules/src/constants/eventsConstants.ts
  packages/grid/x-grid-modules/src/gridComponent.tsx
  packages/grid/x-grid-modules/src/gridComponentProps.ts
  packages/grid/x-grid-modules/src/hooks/features/useComponents.tsx
  packages/grid/x-grid-modules/src/hooks/features/useSorting.ts
  packages/grid/x-grid-modules/src/hooks/root/useApi.ts
  packages/grid/x-grid-modules/src/hooks/root/useEvents.ts
  packages/grid/x-grid-modules/src/models/api/coreApi.ts
  packages/grid/x-grid-modules/src/models/gridComponentOverridesProp.tsx
  packages/grid/x-grid-modules/src/models/gridOptions.tsx
  packages/storybook/src/documentation/pages/demos/demo.css
  packages/storybook/src/documentation/pages/demos/error/customError.demo.tsx
  packages/storybook/src/documentation/pages/demos/error/exception.demo.tsx
  packages/storybook/src/documentation/pages/demos/error/serverError.demo.tsx
  packages/storybook/src/documentation/pages/demos/error/serverErrorState.demo.tsx
  packages/storybook/src/documentation/pages/error-handling.stories.mdx
  packages/storybook/src/documentation/pages/pagination.stories.mdx
  packages/storybook/src/stories/grid-error.stories.tsx
  packages/storybook/src/stories/grid-sorting.stories.tsx
Labels: component: DataGrid

#146 [core] Removing polluting warning
  packages/grid/x-grid-modules/src/hooks/root/useEvents.ts
Labels: component: DataGrid

#149 [DataGrid] Avoid logger noise
  packages/grid/x-grid-modules/src/hooks/features/useApiRef.ts
  packages/grid/x-grid-modules/src/hooks/root/useApi.ts
  packages/grid/x-grid-modules/src/hooks/root/useEvents.ts
Labels: component: DataGrid

#164 [DataGrid] Reverse boolean props to default to false
  packages/grid/data-grid/src/data-grid.tsx
  packages/grid/x-grid-modules/src/components/viewport.tsx
  packages/grid/x-grid-modules/src/gridComponent.tsx
  packages/grid/x-grid-modules/src/hooks/features/useSelection.ts
  packages/grid/x-grid-modules/src/hooks/features/useSorting.ts
  packages/grid/x-grid-modules/src/hooks/utils/useOptionsProp.ts
  packages/grid/x-grid-modules/src/hooks/virtualization/useVirtualColumns.ts
  packages/grid/x-grid-modules/src/models/gridOptions.tsx
  packages/storybook/src/documentation/pages/demos/sorting/serverSorting.demo.tsx
  packages/storybook/src/documentation/pages/quick-start.stories.mdx
  packages/storybook/src/documentation/pages/selection.stories.mdx
  packages/storybook/src/stories/grid-data.stories.tsx
  packages/storybook/src/stories/grid-options.stories.tsx
  packages/storybook/src/stories/grid-pagination.stories.tsx
  packages/storybook/src/stories/grid-selection.stories.tsx
  packages/storybook/src/stories/grid-sorting.stories.tsx
  packages/storybook/src/stories/playground/data-grid.options.stories.tsx
  packages/storybook/src/stories/playground/options.stories.tsx
  packages/storybook/src/stories/playground/real-data-demo.stories.tsx
Labels: breaking change, component: DataGrid

#170 [core] Batch small changes
  docs/scripts/formattedTSDemos.js
  package.json
  packages/grid/x-grid-modules/src/hooks/root/useKeyboard.ts
  packages/storybook/src/documentation/pages/columns.stories.mdx
Labels: core

#178 [test] Fix license warning karma
  packages/grid/data-grid/src/data-grid.tsx
  packages/grid/x-grid/src/grid.tsx
  packages/license/src/generateLicense.ts
  test/utils/init.js
  test/utils/licenseKey.js
  test/utils/licenseRelease.js
Labels: test

#179 [DataGrid] Fix set state leak
  packages/grid/x-grid-modules/src/hooks/utils/useRafUpdate.ts
Labels: bug 🐛, component: DataGrid

#152 [test] CI part of #150
  test/karma.tests.js
  test/utils/consoleError.js
Labels: test

#180 [DataGrid] Avoid inline style
  packages/grid/x-grid-modules/src/components/icons/index.tsx
  packages/grid/x-grid-modules/src/models/gridOptions.tsx
Labels: component: DataGrid

#182 [DataGrid] Use same React version as core
  packages/grid/data-grid/README.md
  packages/grid/data-grid/package.json
  packages/grid/x-grid-data-generator/package.json
  packages/grid/x-grid-modules/package.json
  packages/grid/x-grid/README.md
  packages/grid/x-grid/package.json
  packages/storybook/src/documentation/pages/quick-start.stories.mdx
Labels: component: DataGrid

#181 [core] Improve fs
  babel.config.js
  docs/babel.config.js
  packages/storybook/.storybook/main.js
  packages/x-license/CHANGELOG.md
  packages/x-license/LICENSE.md
  packages/x-license/README.md
  packages/x-license/bin/license-gen-script.js
  packages/x-license/jest.config.js
  packages/x-license/package.json
  packages/x-license/rollup.config.js
  packages/x-license/src/__tests__/base64.tests.ts
  packages/x-license/src/__tests__/generateLicense.tests.ts
  packages/x-license/src/__tests__/md5.tests.ts
  packages/x-license/src/__tests__/verifyLicense.tests.ts
  packages/x-license/src/encoding/base64.ts
  packages/x-license/src/encoding/md5.ts
  packages/x-license/src/generateLicense.ts
  packages/x-license/src/index.ts
  packages/x-license/src/license-cli.ts
  packages/x-license/src/licenseErrorMessageUtils.ts
  packages/x-license/src/licenseInfo.ts
  packages/x-license/src/licenseStatus.ts
  packages/x-license/src/useLicenseVerifier.ts
  packages/x-license/src/verifyLicense.ts
  packages/x-license/tsconfig.json
  tsconfig.json
  webpackBaseConfig.js
Labels: core

#183 [core] Improve script commands
  package.json
Labels: core

#156 [docs] First page
  docs/pages/_app.js
  docs/pages/components/data-grid/accessibility.js
  docs/pages/components/data-grid/index.js
  docs/src/pages.js
  docs/src/pages/components/data-grid/accessibility/accessibility.md
  docs/src/pages/components/data-grid/overview/DataGridDemo.js
  docs/src/pages/components/data-grid/overview/DataGridDemo.tsx
  docs/src/pages/components/data-grid/overview/XGridDemo.js
  docs/src/pages/components/data-grid/overview/XGridDemo.tsx
  docs/src/pages/components/data-grid/overview/overview.md
  packages/grid/data-grid/README.md
  packages/grid/x-grid/README.md
  webpackBaseConfig.js
Labels: docs

#184 [core] Fail CI if wrong effect dependencies
  .eslintrc.js
  packages/grid/x-grid-data-generator/src/useDemoData.ts
  packages/grid/x-grid-modules/src/gridComponent.tsx
  packages/grid/x-grid-modules/src/hooks/features/useApiRef.ts
  packages/grid/x-grid-modules/src/hooks/root/useNativeEventListener.ts
  packages/grid/x-grid-modules/src/hooks/utils/useScrollFn.ts
  packages/storybook/src/components/feed-grid.tsx
  packages/storybook/src/components/pricing-grid.tsx
Labels: test

#185 [DataGrid] Improve forward ref logic
  .mocharc.js
  packages/grid/data-grid/src/DataGrid.test.tsx
  packages/grid/data-grid/src/DataGrid.tsx
  packages/grid/data-grid/src/data-grid.tsx
  packages/grid/data-grid/src/index.ts
  packages/grid/x-grid-modules/src/GridComponent.tsx
  packages/grid/x-grid-modules/src/GridComponentProps.ts
  packages/grid/x-grid-modules/src/hooks/utils/useOptionsProp.ts
  packages/grid/x-grid-modules/src/index.ts
  packages/grid/x-grid/src/XGrid.test.tsx
  packages/grid/x-grid/src/XGrid.tsx
  packages/grid/x-grid/src/index.ts
Labels: bug 🐛, component: DataGrid

#186 [docs] Add missing prism theme
  docs/public/static/images/font-size.gif
  docs/public/static/logo_raw.svg
  docs/public/static/styles/prism-okaidia.css
  package.json
  scripts/importDocsStatic.js
Labels: docs

#188 [DataGrid] Fix SSR support
  packages/grid/x-grid-modules/src/hooks/virtualization/useVirtualRows.ts
Labels: bug 🐛, component: DataGrid

#187 [docs] Polish TypeScript
  .circleci/config.yml
  docs/babel.config.js
  docs/package.json
  docs/pages/components/autocomplete.js
  docs/scripts/formattedTSDemos.js
  docs/src/pages/components/autocomplete/ComboBox.js
  docs/src/pages/components/autocomplete/ComboBox.tsx
  docs/src/pages/components/autocomplete/autocomplete-zh.md
  docs/src/pages/components/autocomplete/autocomplete.md
  docs/src/pages/components/data-grid/overview/DataGridDemo.js
  docs/src/pages/components/data-grid/overview/DataGridDemo.tsx
  docs/src/pages/components/data-grid/overview/XGridDemo.js
  docs/src/pages/components/data-grid/overview/XGridDemo.tsx
  docs/tsconfig.json
  docs/types/docs.d.ts
  docs/types/fg-loadcss.d.ts
  docs/types/icons.d.ts
  package.json
  yarn.lock
Labels: docs, typescript

#189 [DataGrid] Add test case for sorting
  packages/grid/x-grid/src/XGrid.test.tsx
Labels: component: DataGrid, test

#220 [docs] Move the pagination page
  babel.config.js
  docs/babel.config.js
  docs/src/pages/components/data-grid/pagination/AutoPaginationGrid.js
  docs/src/pages/components/data-grid/pagination/AutoPaginationGrid.tsx
  docs/src/pages/components/data-grid/pagination/BasicPaginationGrid.js
  docs/src/pages/components/data-grid/pagination/BasicPaginationGrid.tsx
  docs/src/pages/components/data-grid/pagination/ControlledPaginationGrid.js
  docs/src/pages/components/data-grid/pagination/ControlledPaginationGrid.tsx
  docs/src/pages/components/data-grid/pagination/SizePaginationGrid.js
  docs/src/pages/components/data-grid/pagination/SizePaginationGrid.tsx
  docs/src/pages/components/data-grid/pagination/pagination.md
  packages/grid/x-grid-data-generator/package.json
  packages/grid/x-grid-data-generator/src/commodities.columns.tsx
  packages/grid/x-grid-data-generator/src/employees.columns.tsx
  packages/grid/x-grid-data-generator/src/services/random-generator.ts
  packages/grid/x-grid-data-generator/src/services/real-data-service.ts
  packages/grid/x-grid-data-generator/src/useDemoData.ts
  packages/storybook/src/stories/playground/real-data-demo.stories.tsx
  tsconfig.json
  webpackBaseConfig.js
  yarn.lock
Labels: docs

#222 [docs] Add issue templates
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/1.bug.md
  .github/ISSUE_TEMPLATE/2.feature.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: docs

#224 [docs] Migration of the pagination
  docs/src/pages/components/data-grid/pagination/AutoPaginationGrid.js
  docs/src/pages/components/data-grid/pagination/AutoPaginationGrid.tsx
  docs/src/pages/components/data-grid/pagination/BasicPaginationGrid.js
  docs/src/pages/components/data-grid/pagination/BasicPaginationGrid.tsx
  docs/src/pages/components/data-grid/pagination/ControlledPaginationGrid.js
  docs/src/pages/components/data-grid/pagination/ControlledPaginationGrid.tsx
  docs/src/pages/components/data-grid/pagination/SizePaginationGrid.js
  docs/src/pages/components/data-grid/pagination/SizePaginationGrid.tsx
  docs/src/pages/components/data-grid/pagination/pagination.md
  docs/src/pages/components/data-grid/rendering/CustomPaginationGrid.js
  docs/src/pages/components/data-grid/rendering/CustomPaginationGrid.tsx
  docs/src/pages/components/data-grid/rendering/rendering.md
Labels: docs

#225 [DataGrid] Better explain the limits of MIT vs commercial
  docs/src/pages/components/data-grid/rendering/rendering.md
  package.json
  packages/grid/data-grid/package.json
  packages/grid/data-grid/rollup.config.js
  packages/grid/data-grid/src/DataGrid.spec.tsx
  packages/grid/data-grid/src/DataGrid.test.tsx
  packages/grid/data-grid/src/DataGrid.tsx
  packages/grid/data-grid/tsconfig.build.json
  packages/grid/data-grid/tsconfig.json
  packages/grid/x-grid/package.json
  packages/grid/x-grid/rollup.config.js
  packages/storybook/src/stories/playground/data-grid.options.stories.tsx
  test/utils/index.ts
  test/utils/licenseKey.ts
  test/utils/licenseRelease.ts
  yarn.lock
Labels: component: DataGrid

#227 [test] Add codesandbox-ci
  .codesandbox/ci.json
  package.json
Labels: test

#232 [docs] Continue the migration of the demos
  docs/next.config.js
  docs/src/pages.js
  docs/src/pages/components/data-grid/pagination/ApiRefPaginationGrid.js
  docs/src/pages/components/data-grid/pagination/ApiRefPaginationGrid.tsx
  docs/src/pages/components/data-grid/pagination/ServerPaginationGrid.js
  docs/src/pages/components/data-grid/pagination/ServerPaginationGrid.tsx
  docs/src/pages/components/data-grid/pagination/pagination.md
  packages/grid/data-grid/src/DataGrid.tsx
  packages/grid/x-grid-data-generator/src/useDemoData.ts
  packages/storybook/src/documentation/pages/demos/pagination/autoPageSize.demo.tsx
  packages/storybook/src/documentation/pages/demos/pagination/customPagination.demo.tsx
  packages/storybook/src/documentation/pages/demos/pagination/serverPagination.demo.tsx
  packages/storybook/src/documentation/pages/demos/pagination/setPage.demo.tsx
  packages/storybook/src/documentation/pages/demos/pagination/simplePagination.demo.tsx
  packages/storybook/src/documentation/pages/pagination.stories.mdx
  yarn.lock
Labels: docs

#233 [docs] Migrate sorting
  docs/src/pages/components/data-grid/accessibility/accessibility.md
  docs/src/pages/components/data-grid/pagination/200PaginationGrid.js
  docs/src/pages/components/data-grid/pagination/200PaginationGrid.tsx
  docs/src/pages/components/data-grid/pagination/pagination.md
  docs/src/pages/components/data-grid/rows/BasicSortingGrid.js
  docs/src/pages/components/data-grid/rows/BasicSortingGrid.tsx
  docs/src/pages/components/data-grid/rows/ComparatorSortingGrid.js
  docs/src/pages/components/data-grid/rows/ComparatorSortingGrid.tsx
  docs/src/pages/components/data-grid/rows/DisableSortingGrid.js
  docs/src/pages/components/data-grid/rows/DisableSortingGrid.tsx
  docs/src/pages/components/data-grid/rows/MultiSortingGrid.js
  docs/src/pages/components/data-grid/rows/MultiSortingGrid.tsx
  docs/src/pages/components/data-grid/rows/OrderSortingGrid.js
  docs/src/pages/components/data-grid/rows/OrderSortingGrid.tsx
  docs/src/pages/components/data-grid/rows/ServerSortingGrid.js
  docs/src/pages/components/data-grid/rows/ServerSortingGrid.tsx
  docs/src/pages/components/data-grid/rows/rows.md
  packages/grid/x-grid-data-generator/src/commodities.columns.tsx
  packages/grid/x-grid-modules/src/hooks/features/useSorting.ts
  packages/storybook/src/documentation/pages/demos/sorting/customComparator.demo.tsx
  packages/storybook/src/documentation/pages/demos/sorting/multipleSort.demo.tsx
  packages/storybook/src/documentation/pages/demos/sorting/serverSorting.demo.tsx
  packages/storybook/src/documentation/pages/demos/sorting/singleSort.demo.tsx
  packages/storybook/src/documentation/pages/demos/sorting/sortIndex.demo.tsx
  packages/storybook/src/documentation/pages/demos/sorting/sortModelOption.demo.tsx
  packages/storybook/src/documentation/pages/demos/sorting/sortOrder.demo.tsx
  packages/storybook/src/documentation/pages/demos/sorting/unsortableColumn.demo.tsx
  packages/storybook/src/documentation/pages/sorting.stories.mdx
Labels: docs
