Repository mui/mui-x, pull requests merged in 2021-06, with the labels that each got.

#1529 [docs] Automatically generate API docs
  .circleci/config.yml
  docs/pages/api-docs/data-grid/data-grid.js
  docs/pages/api-docs/data-grid/data-grid.md
  docs/pages/api-docs/data-grid/grid-api.js
  docs/pages/api-docs/data-grid/grid-api.md
  docs/pages/api-docs/data-grid/grid-cell-params.js
  docs/pages/api-docs/data-grid/grid-cell-params.md
  docs/pages/api-docs/data-grid/grid-col-def.js
  docs/pages/api-docs/data-grid/grid-col-def.md
  docs/pages/api-docs/data-grid/grid-filter-api.json
  docs/pages/api-docs/data-grid/grid-row-params.js
  docs/pages/api-docs/data-grid/grid-row-params.md
  docs/pages/api-docs/data-grid/grid-selection-api.json
  docs/pages/api-docs/data-grid/index.js
  docs/pages/api-docs/data-grid/index.md
  docs/pages/api-docs/data-grid/x-grid.js
  docs/pages/api-docs/data-grid/x-grid.md
  docs/pages/components/data-grid/events.js
  docs/scripts/buildApi.js
  docs/scripts/buildApi.ts
  docs/src/modules/components/ApiDocs.js
  docs/src/modules/utils/findPages.js
  docs/src/pages.js
  docs/src/pages/components/data-grid/accessibility/accessibility.md
  docs/src/pages/components/data-grid/columns/columns.md
  docs/src/pages/components/data-grid/components/components.md
  docs/src/pages/components/data-grid/demo/demo.md
  docs/src/pages/components/data-grid/editing/editing.md
  docs/src/pages/components/data-grid/events/CatalogOfEvents.js
  docs/src/pages/components/data-grid/events/SubscribeToEvents.js
  docs/src/pages/components/data-grid/events/SubscribeToEvents.tsx
  docs/src/pages/components/data-grid/events/events.json
  docs/src/pages/components/data-grid/events/events.md
  docs/src/pages/components/data-grid/export/export.md
  docs/src/pages/components/data-grid/filtering/FilterApi.js
  docs/src/pages/components/data-grid/filtering/filtering.md
  docs/src/pages/components/data-grid/getting-started/getting-started.md
  docs/src/pages/components/data-grid/group-pivot/group-pivot.md
  docs/src/pages/components/data-grid/layout/layout.md
  docs/src/pages/components/data-grid/localization/localization.md
  docs/src/pages/components/data-grid/overview/overview.md
  docs/src/pages/components/data-grid/pagination/pagination.md
  docs/src/pages/components/data-grid/rows/rows.md
  docs/src/pages/components/data-grid/selection/SelectionApi.js
  docs/src/pages/components/data-grid/selection/selection.md
  docs/src/pages/components/data-grid/sorting/sorting.md
  docs/src/pages/components/data-grid/style/style.md
  docs/src/pages/components/data-grid/virtualization/virtualization.md
  package.json
  packages/grid/_modules_/grid/models/api/gridCoreApi.ts
  packages/grid/_modules_/grid/models/api/index.ts
  packages/grid/_modules_/grid/models/colDef/gridColDef.ts
  packages/grid/_modules_/grid/utils/eventEmitter/EventEmitter.ts
  webpackBaseConfig.js
  yarn.lock
Labels: docs

#1829 [DataGrid] Fix force reflow on scroll start and end
  packages/grid/_modules_/grid/hooks/utils/useGridScrollFn.ts
Labels: component: DataGrid, performance

#1827 [test] Improve pagination tests
  packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx
Labels: test

#1695 [DataGrid] Allow to customize GridToolbarExport's CSV export
  packages/grid/_modules_/grid/components/toolbar/GridToolbarExport.tsx
  packages/grid/_modules_/grid/hooks/features/export/useGridCsvExport.tsx
  packages/grid/_modules_/grid/models/api/gridCsvExportApi.ts
  packages/grid/_modules_/grid/models/gridExport.ts
Labels: component: DataGrid, enhancement

#1819 [DataGrid] Fix cell height after changing grid's density
  packages/grid/_modules_/grid/components/GridViewport.tsx
  packages/grid/_modules_/grid/components/cell/GridRowCells.tsx
  packages/grid/data-grid/src/tests/toolbar.DataGrid.test.tsx
Labels: bug 🐛, component: DataGrid

#1813 [DataGrid] Deselect row in non checkboxSelection grid
  docs/src/pages/components/data-grid/accessibility/accessibility.md
  docs/src/pages/components/data-grid/selection/selection.md
  packages/grid/_modules_/grid/GridComponent.tsx
  packages/grid/_modules_/grid/hooks/features/core/gridState.ts
  packages/grid/_modules_/grid/hooks/features/keyboard/gridKeyboardSelector.ts
  packages/grid/_modules_/grid/hooks/features/keyboard/gridKeyboardState.ts
  packages/grid/_modules_/grid/hooks/features/keyboard/index.ts
  packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboard.ts
  packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts
  packages/grid/_modules_/grid/hooks/features/sorting/useGridSorting.ts
  packages/grid/_modules_/grid/utils/keyboardUtils.ts
  packages/grid/data-grid/src/tests/selection.DataGrid.test.tsx
Labels: bug 🐛, component: DataGrid

#1816 [DataGrid] Fix fluid columns width when available `viewportWidth` < 0
  packages/grid/_modules_/grid/hooks/features/columns/useGridColumns.ts
Labels: bug 🐛

#1848 [core] Batch small changes
  docs/public/_redirects
  docs/src/pages/components/data-grid/accessibility/accessibility.md
  docs/src/pages/components/data-grid/events/CatalogOfEventsNoSnap.js
  docs/src/pages/components/data-grid/events/events.md
  docs/src/pages/components/data-grid/filtering/FilterApiNoSnap.js
  docs/src/pages/components/data-grid/filtering/filtering.md
  docs/src/pages/components/data-grid/getting-started/getting-started.md
  docs/src/pages/components/data-grid/selection/SelectionApiNoSnap.js
  docs/src/pages/components/data-grid/selection/selection.md
  packages/grid/data-grid/README.md
  packages/grid/data-grid/package.json
  packages/grid/x-grid/README.md
  packages/grid/x-grid/package.json
  test/regressions/index.js
Labels: core, umbrella

#1830 [XGrid] Display the number of filtered rows in the footer
  packages/grid/_modules_/grid/components/GridFooter.tsx
  packages/grid/_modules_/grid/components/GridRowCount.tsx
  packages/grid/_modules_/grid/constants/localeTextConstants.ts
  packages/grid/_modules_/grid/locales/bgBG.ts
  packages/grid/_modules_/grid/locales/csCZ.ts
  packages/grid/_modules_/grid/locales/deDE.ts
  packages/grid/_modules_/grid/locales/elGR.ts
  packages/grid/_modules_/grid/locales/esES.ts
  packages/grid/_modules_/grid/locales/frFR.ts
  packages/grid/_modules_/grid/locales/itIT.ts
  packages/grid/_modules_/grid/locales/jaJP.ts
  packages/grid/_modules_/grid/locales/nlNL.ts
  packages/grid/_modules_/grid/locales/plPL.ts
  packages/grid/_modules_/grid/locales/ptBR.ts
  packages/grid/_modules_/grid/locales/ruRU.ts
  packages/grid/_modules_/grid/locales/skSK.ts
  packages/grid/_modules_/grid/locales/trTR.ts
  packages/grid/_modules_/grid/locales/ukUA.ts
  packages/grid/_modules_/grid/models/api/gridLocaleTextApi.ts
  packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx
Labels: components: XGrid, enhancement

#1856 [docs] Add docs for `disableDensitySelector` option
  docs/pages/api-docs/data-grid/data-grid.md
  docs/pages/api-docs/data-grid/x-grid.md
  packages/grid/_modules_/grid/models/gridOptions.tsx
Labels: component: DataGrid, docs

#1861 [DataGrid] Improve ptBR locale
  packages/grid/_modules_/grid/locales/deDE.ts
  packages/grid/_modules_/grid/locales/frFR.ts
  packages/grid/_modules_/grid/locales/itIT.ts
  packages/grid/_modules_/grid/locales/nlNL.ts
  packages/grid/_modules_/grid/locales/ptBR.ts
Labels: component: DataGrid, enhancement

#1900 [core] Remove dead logic
  packages/grid/_modules_/grid/hooks/features/rows/useGridEditRows.ts
Labels: performance

#1901 [core] Batch small changes
  docs/public/_redirects
  packages/grid/_modules_/grid/components/GridRenderingZone.tsx
  packages/grid/_modules_/grid/components/GridRow.tsx
  packages/grid/_modules_/grid/components/GridViewport.tsx
  packages/grid/_modules_/grid/components/cell/GridCell.tsx
  packages/grid/_modules_/grid/components/cell/GridRowCells.tsx
  packages/grid/_modules_/grid/hooks/features/rows/useGridParamsApi.ts
Labels: core

#1877 [DataGrid] Add useGridApiContext to access the GridApiContext
  packages/grid/_modules_/grid/GridBody.tsx
  packages/grid/_modules_/grid/GridErrorHandler.tsx
  packages/grid/_modules_/grid/GridFooterPlaceholder.tsx
  packages/grid/_modules_/grid/GridHeaderPlaceholder.tsx
  packages/grid/_modules_/grid/GridOverlays.tsx
  packages/grid/_modules_/grid/components/ErrorOverlay.tsx
  packages/grid/_modules_/grid/components/GridApiContext.ts
  packages/grid/_modules_/grid/components/GridFooter.tsx
  packages/grid/_modules_/grid/components/GridHeader.tsx
  packages/grid/_modules_/grid/components/GridNoResultsOverlay.tsx
  packages/grid/_modules_/grid/components/GridNoRowsOverlay.tsx
  packages/grid/_modules_/grid/components/GridPagination.tsx
  packages/grid/_modules_/grid/components/GridRow.tsx
  packages/grid/_modules_/grid/components/GridRowCount.tsx
  packages/grid/_modules_/grid/components/GridScrollArea.tsx
  packages/grid/_modules_/grid/components/GridSelectedRowCount.tsx
  packages/grid/_modules_/grid/components/GridViewport.tsx
  packages/grid/_modules_/grid/components/cell/GridCell.tsx
  packages/grid/_modules_/grid/components/cell/GridRowCells.tsx
  packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderFilterIcon.tsx
  packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderMenuIcon.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderSeparator.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderSortIcon.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaders.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeadersItemCollection.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnUnsortedIcon.tsx
  packages/grid/_modules_/grid/components/columnSelection/GridCellCheckboxRenderer.tsx
  packages/grid/_modules_/grid/components/columnSelection/GridHeaderCheckbox.tsx
  packages/grid/_modules_/grid/components/containers/GridColumnsContainer.tsx
  packages/grid/_modules_/grid/components/containers/GridDataContainer.tsx
  packages/grid/_modules_/grid/components/containers/GridOverlay.tsx
  packages/grid/_modules_/grid/components/containers/GridRoot.tsx
  packages/grid/_modules_/grid/components/containers/GridWindow.tsx
  packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnHeaderMenu.tsx
  packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnsMenuItem.tsx
  packages/grid/_modules_/grid/components/menu/columnMenu/GridFilterMenuItem.tsx
  packages/grid/_modules_/grid/components/menu/columnMenu/HideGridColMenuItem.tsx
  packages/grid/_modules_/grid/components/menu/columnMenu/SortGridMenuItems.tsx
  packages/grid/_modules_/grid/components/panel/GridColumnsPanel.tsx
  packages/grid/_modules_/grid/components/panel/GridPanel.tsx
  packages/grid/_modules_/grid/components/panel/GridPreferencesPanel.tsx
  packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterForm.tsx
  packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterPanel.tsx
  packages/grid/_modules_/grid/components/toolbar/GridToolbar.tsx
  packages/grid/_modules_/grid/components/toolbar/GridToolbarColumnsButton.tsx
  packages/grid/_modules_/grid/components/toolbar/GridToolbarDensitySelector.tsx
  packages/grid/_modules_/grid/components/toolbar/GridToolbarExport.tsx
  packages/grid/_modules_/grid/components/toolbar/GridToolbarFilterButton.tsx
  packages/grid/_modules_/grid/hooks/features/useGridSlotComponentProps.tsx
  packages/grid/_modules_/grid/hooks/root/useGridApiContext.ts
  packages/grid/data-grid/src/tests/components.DataGrid.test.tsx
Labels: component: DataGrid, enhancement

#1880 [docs] Fix 404 links
  docs/pages/api-docs/data-grid/data-grid.md
  docs/pages/api-docs/data-grid/x-grid.md
Labels: docs

#1899 [DataGrid] Escape regular expression characters in filters
  packages/grid/_modules_/grid/models/colDef/gridStringOperators.ts
  packages/grid/data-grid/src/tests/filtering.DataGrid.test.tsx
Labels: bug 🐛, component: DataGrid

#1859 [DataGrid] Allow to set in GridExportCsvOptions delimiter
  packages/grid/_modules_/grid/hooks/features/export/seralizers/csvSeraliser.ts
  packages/grid/_modules_/grid/hooks/features/export/useGridCsvExport.tsx
  packages/grid/_modules_/grid/models/gridExport.ts
  packages/grid/x-grid/src/tests/export.XGrid.test.tsx
Labels: component: DataGrid, enhancement

#1910 [DataGrid] Remove disableClickEventBubbling
  docs/pages/api-docs/data-grid/grid-col-def.md
  packages/grid/_modules_/grid/components/cell/GridCell.tsx
  packages/grid/_modules_/grid/components/columnSelection/GridCellCheckboxRenderer.tsx
  packages/grid/_modules_/grid/models/colDef/gridCheckboxSelection.tsx
  packages/grid/_modules_/grid/models/colDef/gridColDef.ts
  packages/grid/x-grid-data-generator/src/commodities.columns.tsx
  packages/grid/x-grid-data-generator/src/employees.columns.tsx
  packages/grid/x-grid-data-generator/src/renderer/renderLink.tsx
  packages/grid/x-grid/src/tests/events.XGrid.test.tsx
Labels: breaking change, component: DataGrid

#1916 [docs] Fix prop-type warning
  docs/src/pages/components/data-grid/editing/StartEditButtonGrid.js
  docs/src/pages/components/data-grid/editing/StartEditButtonGrid.tsx
Labels: docs

#1917 [DataGrid] Fix support for getRowId on cell editing
  packages/grid/_modules_/grid/hooks/features/rows/useGridEditRows.ts
  packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx
Labels: bug 🐛, component: DataGrid

#1772 [DataGrid] Add support for edit components that use portal
  docs/pages/api-docs/data-grid/grid-api.md
  docs/src/pages/components/data-grid/editing/StartEditButtonGrid.js
  docs/src/pages/components/data-grid/editing/StartEditButtonGrid.tsx
  docs/src/pages/components/data-grid/events/events.json
  packages/grid/_modules_/grid/components/GridRow.tsx
  packages/grid/_modules_/grid/components/cell/GridCell.tsx
  packages/grid/_modules_/grid/constants/eventsConstants.ts
  packages/grid/_modules_/grid/hooks/features/focus/useGridFocus.ts
  packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboard.ts
  packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboardNavigation.ts
  packages/grid/_modules_/grid/hooks/features/rows/useGridEditRows.ts
  packages/grid/_modules_/grid/hooks/root/useApi.ts
  packages/grid/_modules_/grid/hooks/root/useEvents.ts
  packages/grid/_modules_/grid/models/api/gridFocusApi.ts
  packages/grid/_modules_/grid/models/gridOptions.tsx
  packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx
  test/e2e/fixtures/DataGrid/SelectEditCell.tsx
  test/e2e/index.test.ts
Labels: breaking change, bug 🐛, component: DataGrid

#1918 [DataGrid] Improve type of the blur event
  packages/grid/_modules_/grid/models/gridOptions.tsx
Labels: docs, typescript

#1922 [DataGrid] Make the CSV export respect the `valueFormatter`
  packages/grid/_modules_/grid/hooks/features/export/serializers/csvSerializer.ts
  packages/grid/_modules_/grid/hooks/features/export/useGridCsvExport.tsx
  packages/grid/x-grid/src/tests/export.XGrid.test.tsx
Labels: bug 🐛, component: DataGrid

#1913 [DataGrid] Include MUI core component localizations in `localeText`
  docs/pages/api-docs/data-grid/grid-api.md
  docs/src/pages/components/data-grid/localization/localization.md
  packages/grid/_modules_/grid/components/GridPagination.tsx
  packages/grid/_modules_/grid/constants/localeTextConstants.ts
  packages/grid/_modules_/grid/models/api/gridLocaleTextApi.ts
  packages/grid/_modules_/grid/utils/getGridLocalization.ts
Labels: breaking change, bug 🐛, component: DataGrid

#1872 [DataGrid] Rename classes according to new convention
  docs/pages/api-docs/data-grid/data-grid.md
  docs/pages/api-docs/data-grid/x-grid.md
  docs/src/pages/components/data-grid/editing/IsCellEditableGrid.js
  docs/src/pages/components/data-grid/editing/IsCellEditableGrid.tsx
  docs/src/pages/components/data-grid/editing/ValidateCellApiRefGrid.js
  docs/src/pages/components/data-grid/editing/ValidateCellApiRefGrid.tsx
  docs/src/pages/components/data-grid/editing/ValidateRowModelControlGrid.js
  docs/src/pages/components/data-grid/editing/ValidateRowModelControlGrid.tsx
  docs/src/pages/components/data-grid/editing/ValidateServerNameGrid.js
  docs/src/pages/components/data-grid/editing/ValidateServerNameGrid.tsx
  packages/grid/_modules_/grid/components/GridScrollArea.tsx
  packages/grid/_modules_/grid/components/cell/GridCell.tsx
  packages/grid/_modules_/grid/components/cell/GridEditBooleanCell.tsx
  packages/grid/_modules_/grid/components/cell/GridEditInputCell.tsx
  packages/grid/_modules_/grid/components/cell/GridRowCells.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderSeparator.tsx
  packages/grid/_modules_/grid/components/containers/GridDataContainer.tsx
  packages/grid/_modules_/grid/components/containers/GridFooterContainer.tsx
  packages/grid/_modules_/grid/components/containers/GridRootStyles.ts
  packages/grid/_modules_/grid/components/containers/GridToolbarContainer.tsx
  packages/grid/_modules_/grid/components/menu/GridMenu.tsx
  packages/grid/_modules_/grid/components/panel/GridPanel.tsx
  packages/grid/_modules_/grid/components/panel/GridPanelContent.tsx
  packages/grid/_modules_/grid/components/panel/GridPanelFooter.tsx
  packages/grid/_modules_/grid/components/panel/GridPanelWrapper.tsx
  packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterForm.tsx
  packages/grid/_modules_/grid/components/toolbar/GridToolbarFilterButton.tsx
  packages/grid/_modules_/grid/constants/cssClassesConstants.ts
  packages/grid/data-grid/src/tests/components.DataGrid.test.tsx
  packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx
  packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx
  packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx
  packages/grid/x-grid/src/tests/rows.XGrid.test.tsx
  packages/storybook/src/stories/grid-rows.stories.tsx
Labels: breaking change, component: DataGrid

#1923 [DataGrid] Improve updateRows performance
  packages/grid/_modules_/grid/hooks/features/rows/useGridRows.ts
Labels: component: DataGrid, performance

#1903 [DataGrid] Use binary search to find column indexes in virtualization
  packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualColumns.ts
Labels: component: DataGrid, performance

#1928 [test] Fix tests
  packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx
Labels: component: DataGrid, test

#1919 [DataGrid] Fix double-click issue
  packages/grid/_modules_/grid/components/columnSelection/GridHeaderCheckbox.tsx
  packages/grid/x-grid/src/tests/selection.XGrid.test.tsx
Labels: bug 🐛, component: DataGrid

#1932 [test] Test vertical scrollbar
  packages/grid/_modules_/grid/components/GridStickyContainer.tsx
  packages/grid/data-grid/src/tests/layout.DataGrid.test.tsx
  packages/storybook/src/stories/grid-rendering.stories.tsx
Labels: test

#1879 [DataGrid] `Select all` checkbox click should select only filtered rows after filter
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx
  packages/grid/_modules_/grid/components/columnSelection/GridHeaderCheckbox.tsx
  packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts
  packages/grid/x-grid/src/tests/selection.XGrid.test.tsx
Labels: bug 🐛, component: DataGrid

#1862 [DataGrid] Fix events naming
  docs/src/pages/components/data-grid/events/events.json
  packages/grid/_modules_/grid/components/cell/GridCell.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx
  packages/grid/_modules_/grid/components/columnSelection/GridCellCheckboxRenderer.tsx
  packages/grid/_modules_/grid/components/columnSelection/GridHeaderCheckbox.tsx
  packages/grid/_modules_/grid/constants/eventsConstants.ts
  packages/grid/_modules_/grid/hooks/features/columnResize/useGridColumnResize.tsx
  packages/grid/_modules_/grid/hooks/features/columns/useGridColumns.ts
  packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts
  packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboard.ts
  packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboardNavigation.ts
  packages/grid/_modules_/grid/hooks/features/pagination/useGridPagination.ts
  packages/grid/_modules_/grid/hooks/features/rows/useGridEditRows.ts
  packages/grid/_modules_/grid/hooks/features/rows/useGridRows.ts
  packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts
  packages/grid/_modules_/grid/hooks/features/sorting/useGridSorting.ts
  packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualColumns.ts
  packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts
  packages/grid/_modules_/grid/hooks/root/useEvents.ts
  packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx
Labels: breaking change, component: DataGrid

#1925 [DataGrid] Make GRID_ROWS_CLEAR private
  docs/src/pages/components/data-grid/events/events.json
  packages/grid/_modules_/grid/constants/eventsConstants.ts
  packages/grid/_modules_/grid/hooks/features/filter/visibleGridRowsState.ts
  packages/grid/x-grid/src/tests/rows.XGrid.test.tsx
Labels: breaking change, component: DataGrid

#1949 [DataGrid] Fix scrollToIndexes offscreen row
  packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts
  packages/grid/x-grid/src/tests/rows.XGrid.test.tsx
Labels: bug 🐛, component: DataGrid

#1952 [DataGrid] Ignore drag events when disableColumnReorder is true
  packages/grid/_modules_/grid/hooks/features/columnReorder/useGridColumnReorder.tsx
  packages/grid/x-grid/src/tests/reorder.XGrid.test.tsx
  test/e2e/fixtures/DataGrid/ColumnReorder.tsx
  test/e2e/index.test.ts
Labels: bug 🐛, component: DataGrid

#1959 [DataGrid] Fix number edit cell output
  packages/grid/_modules_/grid/models/colDef/gridNumericColDef.ts
  packages/grid/_modules_/grid/models/colDef/gridNumericOperators.ts
  packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx
Labels: component: DataGrid, enhancement

#1963 [docs] Align docs with EULA (source of truth)
  docs/src/pages/components/data-grid/getting-started/getting-started.md
Labels: docs

#1962 [core] Upgrade actions-cool/issues-helper
  .github/workflows/issue-mark-duplicate.yml
Labels: core

#1965 [docs] Fix changing Dataset not working
  docs/src/pages/components/data-grid/demo/FullFeaturedDemo.js
  docs/src/pages/components/data-grid/demo/FullFeaturedDemo.tsx
Labels: docs

#1760 [core] Polish filtering internals
  packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx
  packages/storybook/src/stories/grid-filter.stories.tsx
Labels: component: DataGrid, core

#1969 [DataGrid] Better fix the scrollToIndexes logic
  packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts
  packages/grid/x-grid/src/tests/rows.XGrid.test.tsx
Labels: bug 🐛, component: DataGrid

#1929 [DataGrid] Allow to copy the selected rows to the clipboard
  docs/src/pages/components/data-grid/accessibility/accessibility.md
  packages/grid/_modules_/grid/constants/eventsConstants.ts
  packages/grid/_modules_/grid/hooks/features/clipboard/index.ts
  packages/grid/_modules_/grid/hooks/features/clipboard/useGridClipboard.ts
  packages/grid/_modules_/grid/hooks/features/export/serializers/csvSerializer.ts
  packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboard.ts
  packages/grid/_modules_/grid/hooks/features/rows/useGridEditRows.ts
  packages/grid/_modules_/grid/hooks/features/rows/useGridParamsApi.ts
  packages/grid/_modules_/grid/hooks/root/useEvents.ts
  packages/grid/_modules_/grid/models/api/gridApi.ts
  packages/grid/_modules_/grid/models/api/gridClipboardApi.ts
  packages/grid/_modules_/grid/models/api/index.ts
  packages/grid/_modules_/grid/models/gridExport.ts
  packages/grid/_modules_/grid/useGridComponent.tsx
  packages/grid/x-grid/src/tests/clipboard.XGrid.test.tsx
Labels: component: DataGrid, enhancement

#1988 [core] Fix en_US: virtualised => virtualized
  packages/grid/x-grid/src/tests/rows.XGrid.test.tsx
Labels: core
