Repository mui/mui-x, pull requests merged in 2021-11, with the labels that each got.

#3028 [DataGrid] Add hebrew localization (he-IL)
  docs/src/pages/components/data-grid/localization/localization.md
  packages/grid/_modules_/grid/locales/heIL.ts
  packages/grid/_modules_/grid/locales/index.ts
  scripts/exportsSnapshot.json
Labels: component: DataGrid, enhancement

#3059 [DataGrid] Revert year change in the MIT license
  packages/grid/data-grid/LICENSE
  packages/grid/x-grid-data-generator/LICENSE
Labels: component: DataGrid

#3027 [test] Retry each expect until success
  test/e2e/index.test.ts
Labels: test

#3063 `v4.0.2`
  CHANGELOG.md
  docs/package.json
  lerna.json
  package.json
  packages/eslint-plugin-material-ui/package.json
  packages/grid/data-grid/package.json
  packages/grid/x-grid-data-generator/package.json
  packages/grid/x-grid/package.json
  packages/storybook/package.json
  packages/x-license/package.json
Labels: core

#3025 [DataGrid] is providing the wrong params to event
  packages/grid/_modules_/grid/constants/eventsConstants.ts
  packages/grid/_modules_/grid/hooks/features/editRows/useGridEditRows.ts
Labels: bug 🐛, component: DataGrid

#3058 [docs] Fix the outdated demo of the docs
  docs/src/pages/components/data-grid/getting-started/Codesandbox.js
Labels: docs

#3003 [docs] Explain how to use valueGetter to transform type
  docs/src/pages/components/data-grid/columns/ValueGetterGrid.js
  docs/src/pages/components/data-grid/columns/ValueGetterGrid.tsx
  docs/src/pages/components/data-grid/columns/columns.md
Labels: docs, component: DataGrid

#3055 [core] Group update of MUI Core
  renovate.json
Labels: core

#3068 [core] Ignore *.tsbuildinfo files
  .gitignore
Labels: core

#3002 [core] Prefix selectors from useGridContainerProps with `unstable_`
  packages/grid/_modules_/grid/components/GridVirtualScroller.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaders.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeadersItemCollection.tsx
  packages/grid/_modules_/grid/hooks/features/container/gridContainerSizesSelector.ts
  packages/grid/_modules_/grid/hooks/features/infiniteLoader/useGridInfiniteLoader.ts
  packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboardNavigation.ts
  packages/grid/_modules_/grid/hooks/features/pagination/useGridPageSize.ts
  packages/grid/_modules_/grid/hooks/features/preferencesPanel/gridPreferencePanelSelector.ts
Labels: breaking change, component: DataGrid

#2996 [core] Implement tree-based row management
  docs/pages/api-docs/data-grid/data-grid-pro.json
  docs/pages/api-docs/data-grid/grid-cell-params.md
  docs/translations/api-docs/data-grid/data-grid-pro-pt.json
  docs/translations/api-docs/data-grid/data-grid-pro-zh.json
  docs/translations/api-docs/data-grid/data-grid-pro.json
  docs/translations/api-docs/data-grid/data-grid-pt.json
  docs/translations/api-docs/data-grid/data-grid-zh.json
  docs/translations/api-docs/data-grid/data-grid.json
  packages/grid/_modules_/grid/GridComponentProps.ts
  packages/grid/_modules_/grid/components/GridFooter.tsx
  packages/grid/_modules_/grid/components/GridVirtualScroller.tsx
  packages/grid/_modules_/grid/components/cell/GridBooleanCell.tsx
  packages/grid/_modules_/grid/components/cell/GridEditBooleanCell.tsx
  packages/grid/_modules_/grid/components/cell/GridEditDateCell.tsx
  packages/grid/_modules_/grid/components/cell/GridEditInputCell.tsx
  packages/grid/_modules_/grid/components/cell/GridEditSingleSelectCell.tsx
  packages/grid/_modules_/grid/components/columnSelection/GridCellCheckboxRenderer.tsx
  packages/grid/_modules_/grid/constants/eventsConstants.ts
  packages/grid/_modules_/grid/hooks/core/columnsPreProcessing/gridColumnsPreProcessingApi.ts
  packages/grid/_modules_/grid/hooks/core/rowGroupsPerProcessing/gridRowGroupsPreProcessingApi.ts
  packages/grid/_modules_/grid/hooks/core/rowGroupsPerProcessing/useGridRowGroupsPreProcessing.ts
  packages/grid/_modules_/grid/hooks/features/filter/gridFilterSelector.ts
  packages/grid/_modules_/grid/hooks/features/filter/gridFilterState.ts
  packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts
  packages/grid/_modules_/grid/hooks/features/infiniteLoader/useGridInfiniteLoader.ts
  packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboardNavigation.ts
  packages/grid/_modules_/grid/hooks/features/pagination/gridPaginationSelector.ts
  packages/grid/_modules_/grid/hooks/features/pagination/useGridPage.ts
  packages/grid/_modules_/grid/hooks/features/rows/gridRowsSelector.ts
  packages/grid/_modules_/grid/hooks/features/rows/gridRowsState.ts
  packages/grid/_modules_/grid/hooks/features/rows/useGridParamsApi.ts
  packages/grid/_modules_/grid/hooks/features/rows/useGridRows.ts
  packages/grid/_modules_/grid/hooks/features/sorting/gridSortingSelector.ts
  packages/grid/_modules_/grid/hooks/features/sorting/useGridSorting.ts
  packages/grid/_modules_/grid/hooks/utils/useCurrentPageRows.ts
  packages/grid/_modules_/grid/models/api/gridRowApi.ts
  packages/grid/_modules_/grid/models/colDef/gridColDef.ts
  packages/grid/_modules_/grid/models/gridOptions.tsx
  packages/grid/_modules_/grid/models/gridRows.ts
  packages/grid/_modules_/grid/models/params/gridCellParams.ts
  packages/grid/data-grid/src/DataGrid.tsx
  packages/grid/data-grid/src/DataGridProps.ts
  packages/grid/data-grid/src/useDataGridProps.ts
  packages/grid/x-grid/src/DataGridPro.tsx
  scripts/exportsSnapshot.json
Labels: core, component: DataGrid

#3070 [DataGrid] Fix filtering of nullish numeric cells
  packages/grid/_modules_/grid/models/colDef/gridNumericOperators.ts
  packages/grid/data-grid/src/tests/filtering.DataGrid.test.tsx
Labels: bug 🐛, component: DataGrid

#2918 [DataGrid] GridEditDateCell does not handle timezone correctly
  packages/grid/_modules_/grid/components/cell/GridEditDateCell.tsx
  packages/grid/x-grid/src/tests/editRows.DataGridPro.test.tsx
Labels: bug 🐛, component: DataGrid

#3000 [DataGrid] Prevents bubbling in menu header
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx
  packages/grid/x-grid/src/tests/columnHeaders.DataGridPro.test.tsx
Labels: bug 🐛, component: DataGrid

#3074 [DataGrid] Keyboard navigation broken on page > 0
  packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboardNavigation.ts
  packages/grid/_modules_/grid/utils/utils.ts
  packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx
Labels: bug 🐛, component: DataGrid, regression

#3079 [DataGrid] Move virtualization logic to hook
  packages/grid/_modules_/grid/components/GridVirtualScroller.tsx
  packages/grid/_modules_/grid/components/base/GridBody.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaders.tsx
  packages/grid/_modules_/grid/components/virtualization/GridVirtualScroller.tsx
  packages/grid/_modules_/grid/components/virtualization/GridVirtualScrollerContent.tsx
  packages/grid/_modules_/grid/components/virtualization/GridVirtualScrollerRenderZone.tsx
  packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualScroller.tsx
  packages/grid/data-grid/src/DataGrid.tsx
  packages/grid/data-grid/src/DataGridVirtualScroller.tsx
  packages/grid/x-grid/src/DataGridPro.tsx
  packages/grid/x-grid/src/DataGridProVirtualScroller.tsx
Labels: component: DataGrid

#3084 [core] Use official MUI repo as monorepo dependency
  package.json
  yarn.lock
Labels: core

#3089 v5.0.0-beta.7
  CHANGELOG.md
  benchmark/package.json
  docs/package.json
  lerna.json
  package.json
  packages/eslint-plugin-material-ui/package.json
  packages/grid/data-grid/package.json
  packages/grid/x-grid-data-generator/package.json
  packages/grid/x-grid/package.json
  packages/storybook/package.json
  packages/x-license/package.json
Labels: release

#3078 [DataGrid] Move column headers virtualization to hook
  docs/pages/api-docs/data-grid/data-grid-pro.json
  docs/pages/api-docs/data-grid/data-grid.json
  docs/translations/api-docs/data-grid/data-grid-pro-pt.json
  docs/translations/api-docs/data-grid/data-grid-pro-zh.json
  docs/translations/api-docs/data-grid/data-grid-pro.json
  docs/translations/api-docs/data-grid/data-grid-pt.json
  docs/translations/api-docs/data-grid/data-grid-zh.json
  docs/translations/api-docs/data-grid/data-grid.json
  packages/grid/_modules_/grid/components/base/GridBody.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaders.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeadersInner.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeadersItemCollection.tsx
  packages/grid/_modules_/grid/components/columnHeaders/index.ts
  packages/grid/_modules_/grid/components/containers/GridColumnsContainer.tsx
  packages/grid/_modules_/grid/components/containers/GridRootStyles.ts
  packages/grid/_modules_/grid/components/containers/index.ts
  packages/grid/_modules_/grid/gridClasses.ts
  packages/grid/_modules_/grid/hooks/features/columnHeaders/useGridColumnHeaders.tsx
  packages/grid/_modules_/grid/hooks/features/export/useGridPrintExport.tsx
  packages/grid/data-grid/src/DataGrid.tsx
  packages/grid/data-grid/src/DataGridColumnHeaders.tsx
  packages/grid/x-grid/src/DataGridPro.tsx
  packages/grid/x-grid/src/DataGridProColumnHeaders.tsx
  scripts/exportsSnapshot.json
Labels: breaking change, component: DataGrid

#3072 [docs] Improve `rowCount` CSS doc
  docs/translations/api-docs/data-grid/data-grid-pro-pt.json
  docs/translations/api-docs/data-grid/data-grid-pro-zh.json
  docs/translations/api-docs/data-grid/data-grid-pro.json
  docs/translations/api-docs/data-grid/data-grid-pt.json
  docs/translations/api-docs/data-grid/data-grid-zh.json
  docs/translations/api-docs/data-grid/data-grid.json
  packages/grid/_modules_/grid/gridClasses.ts
Labels: docs

#3090 [core] Use 'unstable_' prefix instead of 'unsafe_'
  packages/grid/_modules_/grid/hooks/core/useGridControlState.ts
  packages/grid/_modules_/grid/hooks/features/clipboard/useGridClipboard.ts
  packages/grid/_modules_/grid/hooks/features/editRows/useGridEditRows.ts
  packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts
  packages/grid/_modules_/grid/hooks/features/pagination/useGridPage.ts
  packages/grid/_modules_/grid/hooks/features/pagination/useGridPageSize.ts
  packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts
  packages/grid/_modules_/grid/hooks/features/sorting/useGridSorting.ts
  packages/grid/_modules_/grid/hooks/utils/useGridState.ts
  packages/grid/_modules_/grid/models/api/gridClipboardApi.ts
  packages/grid/_modules_/grid/models/api/gridControlStateApi.ts
  packages/grid/_modules_/grid/models/api/gridFilterApi.ts
  packages/grid/x-grid/src/tests/clipboard.DataGridPro.test.tsx
Labels: core

#3029 [core] Automatically close issues that are incomplete and inactive
  .github/workflows/close-incomplete-inactive.yml
Labels: core

#3092 [core] Make useGridColumnsPreProcessing generic
  packages/grid/_modules_/grid/constants/eventsConstants.ts
  packages/grid/_modules_/grid/hooks/core/columnsPreProcessing/gridColumnsPreProcessingApi.ts
  packages/grid/_modules_/grid/hooks/core/columnsPreProcessing/index.ts
  packages/grid/_modules_/grid/hooks/core/columnsPreProcessing/useGridColumnsPreProcessing.ts
  packages/grid/_modules_/grid/hooks/core/preProcessing/gridPreProcessingApi.ts
  packages/grid/_modules_/grid/hooks/core/preProcessing/index.ts
  packages/grid/_modules_/grid/hooks/core/preProcessing/useGridPreProcessing.ts
  packages/grid/_modules_/grid/hooks/core/useGridInitialization.ts
  packages/grid/_modules_/grid/hooks/features/columns/useGridColumns.ts
  packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts
  packages/grid/_modules_/grid/models/api/gridApi.ts
Labels: core

#3100 [docs] Fix the client-side validation link clarity
  docs/src/pages/components/data-grid/editing/editing.md
Labels: docs

#3095 [DataGrid] Block multi-rows updates in `apiRef.current.updateRows` on the free plan
  packages/grid/_modules_/grid/hooks/features/rows/useGridRows.ts
Labels: component: DataGrid

#3136 Revert "Bump reselect to ^4.1.2"
  packages/grid/x-data-grid-pro/package.json
  packages/grid/x-data-grid/package.json
  yarn.lock
Labels: dependencies

#3125 [core] Replace createClientRender with new createRenderer API
  packages/grid/_modules_/grid/components/panel/GridPanel.test.tsx
  packages/grid/x-data-grid-pro/src/tests/clipboard.DataGridPro.test.tsx
  packages/grid/x-data-grid-pro/src/tests/columnHeaders.DataGridPro.test.tsx
  packages/grid/x-data-grid-pro/src/tests/columns.DataGridPro.test.tsx
  packages/grid/x-data-grid-pro/src/tests/components.DataGridPro.test.tsx
  packages/grid/x-data-grid-pro/src/tests/editRows.DataGridPro.test.tsx
  packages/grid/x-data-grid-pro/src/tests/events.DataGridPro.test.tsx
  packages/grid/x-data-grid-pro/src/tests/export.DataGridPro.test.tsx
  packages/grid/x-data-grid-pro/src/tests/filtering.DataGridPro.test.tsx
  packages/grid/x-data-grid-pro/src/tests/layout.DataGridPro.test.tsx
  packages/grid/x-data-grid-pro/src/tests/pagination.DataGridPro.test.tsx
  packages/grid/x-data-grid-pro/src/tests/reorder.DataGridPro.test.tsx
  packages/grid/x-data-grid-pro/src/tests/rows.DataGridPro.test.tsx
  packages/grid/x-data-grid-pro/src/tests/selection.DataGridPro.test.tsx
  packages/grid/x-data-grid-pro/src/tests/sorting.DataGridPro.test.tsx
  packages/grid/x-data-grid-pro/src/tests/state.DataGridPro.test.tsx
  packages/grid/x-data-grid/src/tests/cells.DataGrid.test.tsx
  packages/grid/x-data-grid/src/tests/columnHeaders.DataGrid.test.tsx
  packages/grid/x-data-grid/src/tests/columns.spec.tsx
  packages/grid/x-data-grid/src/tests/components.DataGrid.test.tsx
  packages/grid/x-data-grid/src/tests/filtering.DataGrid.test.tsx
  packages/grid/x-data-grid/src/tests/keyboard.DataGrid.test.tsx
  packages/grid/x-data-grid/src/tests/layout.DataGrid.test.tsx
  packages/grid/x-data-grid/src/tests/pagination.DataGrid.test.tsx
  packages/grid/x-data-grid/src/tests/rows.DataGrid.test.tsx
  packages/grid/x-data-grid/src/tests/selection.DataGrid.test.tsx
  packages/grid/x-data-grid/src/tests/sorting.DataGrid.test.tsx
  packages/grid/x-data-grid/src/tests/toolbar.DataGrid.test.tsx
  test/utils/index.tsx
  yarn.lock
Labels: test, core

#3086 [DataGrid] Keyboard navigation between header and rows is broken on page > 0
  packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboardNavigation.ts
  packages/grid/x-data-grid/src/tests/keyboard.DataGrid.test.tsx
Labels: bug 🐛, component: DataGrid

#3123 [docs] Fix example in 'data-grid'
  docs/src/pages/components/data-grid/components/components.md
Labels: docs, component: DataGrid

#3139 [core] Update monorepo
  docs/tsconfig.tsbuildinfo
  yarn.lock
Labels: PR: on hold, core

#3143 [docs] Use core repo intl constants
  docs/pages/_app.js
  docs/src/modules/constants.js
Labels: bug 🐛, docs, regression

#3127 [DataGrid] Fix `updateRows` to not use rows from other instances
  packages/grid/_modules_/grid/hooks/features/rows/useGridRows.ts
Labels: component: DataGrid

#3018 [DataGrid] Fix filter not working after deleting the value
  packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterInputValue.tsx
  packages/grid/_modules_/grid/models/colDef/gridNumericColDef.ts
  packages/grid/x-data-grid-pro/src/tests/filtering.DataGridPro.test.tsx
  packages/grid/x-data-grid/src/tests/filtering.DataGrid.test.tsx
Labels: bug 🐛, component: DataGrid

#3142 [DataGrid] Rename `Checkbox` component and props slots to `BaseCheckbox`
  docs/pages/api-docs/data-grid/data-grid-pro.json
  docs/pages/api-docs/data-grid/data-grid.json
  docs/translations/api-docs/data-grid/data-grid-pro-pt.json
  docs/translations/api-docs/data-grid/data-grid-pro-zh.json
  docs/translations/api-docs/data-grid/data-grid-pro.json
  docs/translations/api-docs/data-grid/data-grid-pt.json
  docs/translations/api-docs/data-grid/data-grid-zh.json
  docs/translations/api-docs/data-grid/data-grid.json
  packages/grid/_modules_/grid/components/columnSelection/GridCellCheckboxRenderer.tsx
  packages/grid/_modules_/grid/components/columnSelection/GridHeaderCheckbox.tsx
  packages/grid/_modules_/grid/hooks/utils/useGridProcessedProps.ts
  packages/grid/_modules_/grid/models/gridSlotsComponent.ts
  packages/grid/_modules_/grid/models/gridSlotsComponentsProps.ts
Labels: breaking change, component: DataGrid, components: DataGridPro

#3099 [DataGrid] Flex space allocation should never cause horizontal scroll when their is enough space
  packages/grid/_modules_/grid/hooks/features/columns/useGridColumns.ts
  packages/grid/x-data-grid/src/tests/layout.DataGrid.test.tsx
Labels: bug 🐛, component: DataGrid

#3133 [DataGrid] Remove unused rendering state and selectors
  packages/grid/_modules_/grid/hooks/features/index.ts
  packages/grid/_modules_/grid/hooks/features/virtualization/index.ts
  packages/grid/_modules_/grid/hooks/features/virtualization/renderingState.ts
  packages/grid/_modules_/grid/hooks/features/virtualization/renderingStateSelector.ts
  packages/grid/_modules_/grid/models/gridState.ts
  scripts/exportsSnapshot.json
Labels: component: DataGrid

#3141 [core] Improve `getLicenseErrorMessage` param type
  packages/grid/_modules_/grid/components/Watermark.tsx
Labels: core, components: DataGridPro

#3145 [test] Use interval for `waitFor` in test:e2e
  test/e2e/index.test.ts
Labels: test

#3057 [core] Improve playground
  .gitignore
  docs/pages/playground.example.tsx
  docs/pages/playground.tsx
Labels: core

#3132 [docs] Migration guide from v4 to v5
  docs/pages/components/data-grid/migration-v4.js
  docs/src/pages.js
  docs/src/pages/components/data-grid/getting-started/getting-started.md
  docs/src/pages/components/data-grid/getting-started/migration-v4.md
Labels: docs

#3151 [core] Fix the support request GitHub Action
  .github/support.yml
  .github/workflows/support.yml
Labels: core

#3160 v5.0.0
  CHANGELOG.md
  benchmark/package.json
  docs/package.json
  lerna.json
  package.json
  packages/eslint-plugin-material-ui/package.json
  packages/grid/x-data-grid-generator/package.json
  packages/grid/x-data-grid-pro/package.json
  packages/grid/x-data-grid/package.json
  packages/storybook/package.json
  packages/x-license-pro/package.json
Labels: release

#3146 [DataGrid] Use color-scheme to set dark mode on native components
  packages/grid/_modules_/grid/components/containers/GridRootStyles.ts
Labels: component: DataGrid, enhancement

#3165 [core] Remove the index.ts of the export hooks
  packages/grid/_modules_/grid/hooks/features/export/index.ts
Labels: core

#3126 [core] Move `apiRef.current.getRowIdFromRowIndex` and `apiRef.current.getRowIndex` to the sorting API
  docs/pages/api-docs/data-grid/grid-api.md
  packages/grid/_modules_/grid/hooks/features/rows/useGridRows.ts
  packages/grid/_modules_/grid/hooks/features/sorting/useGridSorting.ts
  packages/grid/_modules_/grid/models/api/gridRowApi.ts
  packages/grid/_modules_/grid/models/api/gridSortApi.ts
Labels: core, component: DataGrid

#3007 [core] Drop `useGridContainerProps`
  docs/pages/api-docs/data-grid/grid-api.md
  docs/src/pages/components/data-grid/events/events.json
  packages/grid/_modules_/grid/components/GridRow.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeadersInner.tsx
  packages/grid/_modules_/grid/components/containers/GridOverlay.tsx
  packages/grid/_modules_/grid/constants/eventsConstants.ts
  packages/grid/_modules_/grid/hooks/features/columnHeaders/useGridColumnHeaders.tsx
  packages/grid/_modules_/grid/hooks/features/columns/useGridColumns.ts
  packages/grid/_modules_/grid/hooks/features/container/gridContainerSizesSelector.ts
  packages/grid/_modules_/grid/hooks/features/container/useGridContainerProps.ts
  packages/grid/_modules_/grid/hooks/features/dimensions/gridDimensionsApi.ts
  packages/grid/_modules_/grid/hooks/features/dimensions/index.ts
  packages/grid/_modules_/grid/hooks/features/dimensions/useGridDimensions.ts
  packages/grid/_modules_/grid/hooks/features/index.ts
  packages/grid/_modules_/grid/hooks/features/infiniteLoader/useGridInfiniteLoader.ts
  packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboardNavigation.ts
  packages/grid/_modules_/grid/hooks/features/pagination/useGridPage.ts
  packages/grid/_modules_/grid/hooks/features/pagination/useGridPageSize.ts
  packages/grid/_modules_/grid/hooks/features/resize/useGridResizeContainer.ts
  packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualScroller.tsx
  packages/grid/_modules_/grid/hooks/utils/useCurrentPageRows.ts
  packages/grid/_modules_/grid/models/api/gridApi.ts
  packages/grid/_modules_/grid/models/api/gridEventsApi.ts
  packages/grid/_modules_/grid/models/api/index.ts
  packages/grid/_modules_/grid/models/gridContainerProps.ts
  packages/grid/_modules_/grid/models/gridState.ts
  packages/grid/_modules_/grid/models/index.ts
  packages/grid/x-data-grid-pro/src/tests/rows.DataGridPro.test.tsx
  packages/grid/x-data-grid-pro/src/useDataGridProComponent.tsx
  packages/grid/x-data-grid/src/tests/keyboard.DataGrid.test.tsx
  packages/grid/x-data-grid/src/useDataGridComponent.tsx
  scripts/exportsSnapshot.json
  test/regressions/TestViewer.js
Labels: core, component: DataGrid

#3196 [DataGrid] Fix the `@mui/x-data-grid` type entrypoint
  packages/grid/rollup.x-data-grid.config.js
Labels: bug 🐛, component: DataGrid

#3192 [core] Set the correct release date for v5.0.0 in the CHANGELOG.md
  CHANGELOG.md
Labels: core

#3169 [DataGrid] Update elGR locale
  packages/grid/_modules_/grid/locales/elGR.ts
Labels: component: DataGrid

#3204 [DataGrid] Do not skip column header renderContext update when the column to render have changed
  packages/grid/_modules_/grid/hooks/features/columnHeaders/useGridColumnHeaders.tsx
Labels: bug 🐛, component: DataGrid

#3187 [core] Improve testing of the keyboard navigation
  packages/grid/x-data-grid/src/tests/keyboard.DataGrid.test.tsx
  test/utils/helperFn.ts
Labels: test, core

#3193 [DataGrid] Rework keyboard navigation
  packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboardNavigation.ts
Labels: core, component: DataGrid

#3232 [l10n] Improve ko_KR locale
  packages/grid/_modules_/grid/locales/koKR.ts
Labels: l10n

#3214 [docs] Fix typo in CHANGELOG.md
  CHANGELOG.md
Labels: docs

#3230 [l10n] Add missing translation for de_DE locale
  packages/grid/_modules_/grid/locales/deDE.ts
Labels: l10n

#3191 [docs] Include row pinning
  docs/src/pages/components/data-grid/columns/columns.md
  docs/src/pages/components/data-grid/getting-started/getting-started.md
  docs/src/pages/components/data-grid/rows/rows.md
Labels: docs, pro plan

#3189 [core] Split `buildApi.ts`
  docs/scripts/api/buildApi.ts
  docs/scripts/api/buildComponentDocumentation.ts
  docs/scripts/api/buildExportsDocumentation.ts
  docs/scripts/api/buildInterfacesDocumentation.ts
  docs/scripts/api/utils.ts
  docs/scripts/buildApi.ts
  docs/scripts/tsconfig.json
  docs/translations/api-docs/data-grid/data-grid-de.json
  docs/translations/api-docs/data-grid/data-grid-es.json
  docs/translations/api-docs/data-grid/data-grid-fr.json
  docs/translations/api-docs/data-grid/data-grid-ja.json
  docs/translations/api-docs/data-grid/data-grid-pro-de.json
  docs/translations/api-docs/data-grid/data-grid-pro-es.json
  docs/translations/api-docs/data-grid/data-grid-pro-fr.json
  docs/translations/api-docs/data-grid/data-grid-pro-ja.json
  docs/translations/api-docs/data-grid/data-grid-pro-ru.json
  docs/translations/api-docs/data-grid/data-grid-ru.json
  package.json
Labels: core

#3213 [DataGrid] Do not debounce the initial resizing of the grid
  packages/grid/_modules_/grid/hooks/features/dimensions/useGridDimensions.ts
Labels: component: DataGrid, regression

#3235 [core] Reflect the change of default branch
  docs/README.md
  docs/next.config.js
Labels: core

#3273 [l10n] Improve ko_KR locale
  packages/grid/_modules_/grid/locales/koKR.ts
Labels: l10n

#3271 [l10n] Add missing translation for de_DE locale (2)
  packages/grid/_modules_/grid/locales/deDE.ts
Labels: l10n

#3261 [DataGrid] Set min dimensions to GridOverlay when no rows provided and autoHeight = true
  packages/grid/_modules_/grid/components/containers/GridOverlay.tsx
  packages/grid/x-data-grid/src/tests/layout.DataGrid.test.tsx
Labels: bug 🐛, component: DataGrid

#3283 [test] Force effect to run on location change
  test/regressions/TestViewer.js
  test/regressions/index.test.js
Labels: test

#3124 [docs] Row and cell editing new examples for server-side persistence
  docs/src/pages/components/data-grid/editing/CellEditServerSidePersistence.js
  docs/src/pages/components/data-grid/editing/CellEditServerSidePersistence.tsx
  docs/src/pages/components/data-grid/editing/CellEditServerSidePersistence.tsx.preview
  docs/src/pages/components/data-grid/editing/RowEditServerSidePersistence.js
  docs/src/pages/components/data-grid/editing/RowEditServerSidePersistence.tsx
  docs/src/pages/components/data-grid/editing/RowEditServerSidePersistence.tsx.preview
  docs/src/pages/components/data-grid/editing/editing.md
Labels: docs, components: DataGridPro

#3217 [core] Replace @mui/core with @mui/base
  packages/grid/x-data-grid-generator/package.json
  packages/grid/x-data-grid-generator/src/renderer/renderEditProgress.tsx
  packages/grid/x-data-grid-pro/src/tests/editRows.DataGridPro.test.tsx
  packages/grid/x-data-grid-pro/src/tests/events.DataGridPro.test.tsx
  packages/grid/x-data-grid/src/tests/filtering.DataGrid.test.tsx
  packages/grid/x-data-grid/src/tests/pagination.DataGrid.test.tsx
  renovate.json
  yarn.lock
Labels: core

#3288 [l10n] Update ruRU locale
  packages/grid/_modules_/grid/locales/ruRU.ts
Labels: l10n

#3290 [l10n] Improve Update ruRU locale
  packages/grid/_modules_/grid/locales/ruRU.ts
Labels: l10n

#3269 [docs] Fix the wrong release date of v5.0.0 and v5.0.1
  CHANGELOG.md
Labels: bug 🐛, docs

#3278 [DataGridPro] Improve license file
  packages/grid/x-data-grid-pro/LICENSE
  packages/grid/x-data-grid-pro/LICENSE.md
  packages/x-license-pro/LICENSE
  packages/x-license-pro/LICENSE.md
Labels: components: DataGridPro

#3294 [l10n] Improve Hebrew (he_IL) locale
  packages/grid/_modules_/grid/locales/heIL.ts
Labels: component: DataGrid, l10n

#3293 [l10n] Improve German (de_DE) locale
  packages/grid/_modules_/grid/locales/deDE.ts
Labels: l10n

#3300 [docs] Fix broken images
  docs/src/pages/components/data-grid/getting-started/getting-started.md
Labels: bug 🐛, docs

#3299 [docs] Use relative links
  docs/src/pages/components/data-grid/getting-started/migration-v4.md
  docs/src/pages/components/data-grid/localization/localization.md
  docs/src/pages/components/data-grid/overview/overview.md
Labels: docs

#3301 [DataGrid] Prepare the tree structure for grouping sorting / filtering + multi field grouping
  docs/scripts/generateProptypes.ts
  docs/src/pages/components/data-grid/group-pivot/CustomGroupingColumnTreeData.js
  docs/src/pages/components/data-grid/group-pivot/CustomGroupingColumnTreeData.tsx
  packages/grid/_modules_/grid/components/cell/GridTreeDataGroupingCell.tsx
  packages/grid/_modules_/grid/components/columnSelection/GridCellCheckboxRenderer.tsx
  packages/grid/_modules_/grid/hooks/core/rowGroupsPerProcessing/useGridRowGroupsPreProcessing.ts
  packages/grid/_modules_/grid/hooks/features/treeData/gridTreeDataGroupColDef.tsx
  packages/grid/_modules_/grid/hooks/features/treeData/useGridTreeData.ts
  packages/grid/_modules_/grid/models/colDef/gridColDef.ts
  packages/grid/_modules_/grid/models/gridRows.ts
  packages/grid/_modules_/grid/utils/tree/buildRowTree.test.ts
  packages/grid/_modules_/grid/utils/tree/buildRowTree.ts
  packages/grid/x-data-grid-pro/src/tests/columnHeaders.DataGridPro.test.tsx
  scripts/exportsSnapshot.json
Labels: components: DataGridPro

#3298 [docs] Improve plan icon placement
  docs/src/modules/XWrapper.js
  docs/src/pages/components/data-grid/columns/columns.md
  docs/src/pages/components/data-grid/editing/editing.md
  docs/src/pages/components/data-grid/events/events.md
  docs/src/pages/components/data-grid/export/export.md
  docs/src/pages/components/data-grid/filtering/filtering.md
  docs/src/pages/components/data-grid/getting-started/getting-started.md
  docs/src/pages/components/data-grid/group-pivot/group-pivot.md
  docs/src/pages/components/data-grid/overview/overview.md
  docs/src/pages/components/data-grid/pagination/pagination.md
  docs/src/pages/components/data-grid/rows/rows.md
  docs/src/pages/components/data-grid/scrolling/scrolling.md
  docs/src/pages/components/data-grid/selection/selection.md
  docs/src/pages/components/data-grid/sorting/sorting.md
  docs/src/pages/components/data-grid/virtualization/virtualization.md
Labels: docs

#3274 [docs] Replace @mui/styles on demos
  docs/src/pages/components/data-grid/columns/CustomColumnTypesGrid.js
  docs/src/pages/components/data-grid/columns/CustomColumnTypesGrid.tsx
  docs/src/pages/components/data-grid/columns/RenderExpandCellGrid.js
  docs/src/pages/components/data-grid/columns/RenderExpandCellGrid.tsx
  docs/src/pages/components/data-grid/components/CustomColumnMenu.js
  docs/src/pages/components/data-grid/components/CustomColumnMenu.tsx
  docs/src/pages/components/data-grid/components/CustomEmptyOverlayGrid.js
  docs/src/pages/components/data-grid/components/CustomEmptyOverlayGrid.tsx
  docs/src/pages/components/data-grid/components/CustomFooter.js
  docs/src/pages/components/data-grid/components/CustomFooter.tsx
  docs/src/pages/components/data-grid/components/CustomPaginationGrid.js
  docs/src/pages/components/data-grid/components/CustomPaginationGrid.tsx
  docs/src/pages/components/data-grid/demo/FullFeaturedDemo.js
  docs/src/pages/components/data-grid/demo/FullFeaturedDemo.tsx
  docs/src/pages/components/data-grid/editing/ConditionalValidationGrid.js
  docs/src/pages/components/data-grid/editing/ConditionalValidationGrid.tsx
  docs/src/pages/components/data-grid/editing/ConditionalValidationGrid.tsx.preview
  docs/src/pages/components/data-grid/editing/FullFeaturedCrudGrid.js
  docs/src/pages/components/data-grid/editing/FullFeaturedCrudGrid.tsx
  docs/src/pages/components/data-grid/editing/IsCellEditableGrid.js
  docs/src/pages/components/data-grid/editing/IsCellEditableGrid.tsx
  docs/src/pages/components/data-grid/editing/IsCellEditableGrid.tsx.preview
  docs/src/pages/components/data-grid/editing/RenderRatingEditCellGrid.js
  docs/src/pages/components/data-grid/editing/RenderRatingEditCellGrid.tsx
  docs/src/pages/components/data-grid/editing/StartEditButtonGrid.js
  docs/src/pages/components/data-grid/editing/StartEditButtonGrid.tsx
  docs/src/pages/components/data-grid/editing/ValidateRowModelControlGrid.js
  docs/src/pages/components/data-grid/editing/ValidateRowModelControlGrid.tsx
  docs/src/pages/components/data-grid/editing/ValidateRowModelControlGrid.tsx.preview
  docs/src/pages/components/data-grid/editing/ValidateServerNameGrid.js
  docs/src/pages/components/data-grid/editing/ValidateServerNameGrid.tsx
  docs/src/pages/components/data-grid/editing/ValidateServerNameGrid.tsx.preview
  docs/src/pages/components/data-grid/filtering/CustomRatingOperator.js
  docs/src/pages/components/data-grid/filtering/CustomRatingOperator.tsx
  docs/src/pages/components/data-grid/filtering/ExtendNumericOperator.js
  docs/src/pages/components/data-grid/filtering/ExtendNumericOperator.tsx
  docs/src/pages/components/data-grid/filtering/QuickFilteringGrid.js
  docs/src/pages/components/data-grid/filtering/QuickFilteringGrid.tsx
  docs/src/pages/components/data-grid/style/AntDesignGrid.js
  docs/src/pages/components/data-grid/style/AntDesignGrid.tsx
  docs/src/pages/components/data-grid/style/AntDesignGrid.tsx.preview
  docs/src/pages/components/data-grid/style/StylingAllCells.js
  docs/src/pages/components/data-grid/style/StylingAllCells.tsx
  docs/src/pages/components/data-grid/style/StylingCellsGrid.js
  docs/src/pages/components/data-grid/style/StylingCellsGrid.tsx
  docs/src/pages/components/data-grid/style/StylingHeaderGrid.js
  docs/src/pages/components/data-grid/style/StylingHeaderGrid.tsx
  docs/src/pages/components/data-grid/style/StylingRowsGrid.js
  docs/src/pages/components/data-grid/style/StylingRowsGrid.tsx
Labels: docs

#3297 [docs] Key conbinations should have a nested kbd
  docs/src/pages/components/data-grid/accessibility/accessibility.md
Labels: docs, accessibility

#3281 [DataGrid] Add support for `sx` prop
  docs/pages/api-docs/data-grid/data-grid-pro.json
  docs/pages/api-docs/data-grid/data-grid.json
  docs/scripts/api/buildComponentDocumentation.ts
  docs/src/pages/components/data-grid/style/SxProp.js
  docs/src/pages/components/data-grid/style/SxProp.tsx
  docs/src/pages/components/data-grid/style/SxProp.tsx.preview
  docs/src/pages/components/data-grid/style/style.md
  docs/translations/api-docs/data-grid/data-grid-pro-pt.json
  docs/translations/api-docs/data-grid/data-grid-pro-zh.json
  docs/translations/api-docs/data-grid/data-grid-pro.json
  docs/translations/api-docs/data-grid/data-grid-pt.json
  docs/translations/api-docs/data-grid/data-grid-zh.json
  docs/translations/api-docs/data-grid/data-grid.json
  packages/grid/_modules_/grid/GridComponentProps.ts
  packages/grid/_modules_/grid/components/containers/GridRoot.tsx
  packages/grid/x-data-grid-pro/package.json
  packages/grid/x-data-grid-pro/src/DataGridPro.tsx
  packages/grid/x-data-grid-pro/src/tests/DataGridPro.spec.tsx
  packages/grid/x-data-grid-pro/src/tests/layout.DataGridPro.test.tsx
  packages/grid/x-data-grid/package.json
  packages/grid/x-data-grid/src/DataGrid.tsx
  packages/grid/x-data-grid/src/tests/DataGrid.spec.tsx
  packages/grid/x-data-grid/src/tests/layout.DataGrid.test.tsx
  scripts/exportsSnapshot.json
Labels: component: DataGrid, enhancement
