Repository mui/mui-x, pull requests merged in 2021-05, with the labels that each got.

#1515 [docs] Fix focus isn't set on the text box in `Edit using external button` demo
  docs/src/pages/components/data-grid/editing/StartEditButtonGrid.js
  docs/src/pages/components/data-grid/editing/StartEditButtonGrid.tsx
Labels: bug 🐛, docs

#1530 [core] Update monorepo
  yarn.lock
Labels: core

#1531 [docs] Header convention for controllable prop
  docs/src/pages/components/data-grid/editing/editing.md
Labels: docs

#1532 [test] Increase timeout on jsdom
  .mocharc.js
Labels: test

#1563 [docs] Fix typo of `onColumnResizeCommitted` prop
  docs/pages/api-docs/data-grid.md
  docs/pages/api-docs/x-grid.md
  docs/src/pages/components/data-grid/rows/rows.md
Labels: bug 🐛, docs

#1566 [core] Improve GridApi type structure
  packages/grid/_modules_/grid/models/api/gridApi.ts
Labels: typescript

#1528 [DataGrid] Support Checkbox component slot
  docs/pages/api-docs/data-grid.md
  docs/pages/api-docs/x-grid.md
  packages/grid/_modules_/grid/components/columnSelection/GridCellCheckboxRenderer.tsx
  packages/grid/_modules_/grid/components/columnSelection/GridHeaderCheckbox.tsx
  packages/grid/_modules_/grid/hooks/features/useGridComponents.tsx
  packages/grid/_modules_/grid/models/api/gridComponentsApi.ts
  packages/grid/_modules_/grid/models/gridSlotsComponent.ts
  packages/grid/_modules_/grid/models/gridSlotsComponentsProps.ts
  packages/storybook/src/stories/playground/customComponents.tsx
  packages/storybook/src/stories/playground/customize-components.stories.tsx
Labels: component: DataGrid, enhancement

#1578 [DataGrid] Add `onColumnVisibilityChange` prop
  docs/pages/api-docs/data-grid.md
  docs/pages/api-docs/x-grid.md
  packages/grid/_modules_/grid/components/menu/columnMenu/HideGridColMenuItem.tsx
  packages/grid/_modules_/grid/components/panel/GridColumnsPanel.tsx
  packages/grid/_modules_/grid/constants/eventsConstants.ts
  packages/grid/_modules_/grid/hooks/features/columns/useGridColumns.ts
  packages/grid/_modules_/grid/models/api/gridColumnApi.ts
  packages/grid/_modules_/grid/models/gridOptions.tsx
  packages/grid/_modules_/grid/models/params/gridColumnVisibilityChangeParams.ts
Labels: breaking change, component: DataGrid, enhancement

#1552 [core] Simplify component type
  docs/pages/api-docs/data-grid.md
  docs/pages/api-docs/x-grid.md
  packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnHeaderMenu.tsx
  packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterForm.tsx
  packages/grid/_modules_/grid/models/api/gridComponentsApi.ts
  packages/grid/_modules_/grid/models/gridFilterOperator.ts
  packages/grid/_modules_/grid/models/gridIconSlotsComponent.ts
  packages/grid/_modules_/grid/models/gridSlotsComponent.ts
Labels: core, typescript

#1588 [core] Add security policy
  SECURITY.md
Labels: core

#1585 [docs] Fix errors in the docs
  packages/grid/_modules_/grid/models/colDef/gridColDef.ts
Labels: docs

#1616 v4.0.0-alpha.28
  CHANGELOG.md
  docs/package.json
  lerna.json
  package.json
  packages/eslint-plugin-material-ui/package.json
  packages/grid/data-grid/package.json
  packages/grid/x-grid-data-generator/package.json
  packages/grid/x-grid/package.json
  packages/storybook/package.json
  packages/x-license/package.json
Labels: core

#1587 [DataGrid] Fix broken checkbox in Material-UI v5
  packages/grid/_modules_/grid/components/cell/GridEditBooleanCell.tsx
  packages/grid/_modules_/grid/components/columnSelection/GridCellCheckboxRenderer.tsx
  packages/grid/_modules_/grid/components/columnSelection/GridHeaderCheckbox.tsx
Labels: bug 🐛, component: DataGrid

#1589 [docs] Refine the descriptions to be clearer
  docs/src/pages/components/data-grid/overview/overview.md
Labels: docs

#1619 [core] Fix dependabot config
  .github/dependabot.yml
Labels: core

#1513 [DataGrid] Performance optimization
  docs/src/pages/components/data-grid/columns/ValueGetterGrid.js
  docs/src/pages/components/data-grid/columns/ValueGetterGrid.tsx
  docs/src/pages/components/data-grid/editing/CatchEditingEventsGrid.js
  docs/src/pages/components/data-grid/editing/CatchEditingEventsGrid.tsx
  docs/src/pages/components/data-grid/editing/ValueGetterGrid.js
  docs/src/pages/components/data-grid/editing/ValueGetterGrid.tsx
  docs/src/pages/components/data-grid/overview/DataGridDemo.js
  docs/src/pages/components/data-grid/overview/DataGridDemo.tsx
  docs/src/pages/components/data-grid/rows/StylingRowsGrid.js
  docs/src/pages/components/data-grid/rows/StylingRowsGrid.tsx
  docs/src/pages/components/data-grid/sorting/ComparatorSortingGrid.js
  docs/src/pages/components/data-grid/sorting/ComparatorSortingGrid.tsx
  packages/grid/_modules_/grid/components/GridViewport.tsx
  packages/grid/_modules_/grid/components/cell/GridBooleanCell.tsx
  packages/grid/_modules_/grid/components/cell/GridCell.tsx
  packages/grid/_modules_/grid/components/cell/GridEditBooleanCell.tsx
  packages/grid/_modules_/grid/components/cell/GridEditInputCell.tsx
  packages/grid/_modules_/grid/components/cell/GridRowCells.tsx
  packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderFilterIcon.tsx
  packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderMenuIcon.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeadersItemCollection.tsx
  packages/grid/_modules_/grid/components/columnSelection/GridCellCheckboxRenderer.tsx
  packages/grid/_modules_/grid/components/columnSelection/GridHeaderCheckbox.tsx
  packages/grid/_modules_/grid/constants/eventsConstants.ts
  packages/grid/_modules_/grid/hooks/features/focus/gridFocusState.ts
  packages/grid/_modules_/grid/hooks/features/focus/gridFocusStateSelector.ts
  packages/grid/_modules_/grid/hooks/features/focus/useGridFocus.ts
  packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboard.ts
  packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboardNavigation.ts
  packages/grid/_modules_/grid/hooks/features/rows/useGridEditRows.ts
  packages/grid/_modules_/grid/hooks/features/rows/useGridParamsApi.ts
  packages/grid/_modules_/grid/hooks/features/rows/useGridRows.ts
  packages/grid/_modules_/grid/hooks/features/sorting/useGridSorting.ts
  packages/grid/_modules_/grid/models/api/gridFocusApi.ts
  packages/grid/_modules_/grid/models/api/gridRowApi.ts
  packages/grid/_modules_/grid/models/gridSortModel.ts
  packages/grid/_modules_/grid/models/params/gridCellParams.ts
  packages/grid/_modules_/grid/models/params/gridColumnHeaderParams.ts
  packages/grid/_modules_/grid/models/params/gridRowParams.ts
  packages/grid/_modules_/grid/utils/sortingUtils.ts
  packages/grid/data-grid/src/tests/layout.DataGrid.test.tsx
  packages/grid/data-grid/src/tests/rows.DataGrid.test.tsx
  packages/grid/x-grid/src/tests/events.XGrid.test.tsx
  packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx
  packages/grid/x-grid/src/tests/sorting.XGrid.test.tsx
  packages/storybook/src/stories/grid-columns.stories.tsx
  packages/storybook/src/stories/grid-error.stories.tsx
  packages/storybook/src/stories/grid-rows.stories.tsx
  packages/storybook/src/stories/grid-sorting.stories.tsx
  packages/storybook/src/stories/grid-style.stories.tsx
  packages/storybook/src/stories/playground/customize-components.stories.tsx
  packages/storybook/src/stories/playground/real-data-demo.stories.tsx
Labels: breaking change, bug 🐛, performance

#1624 [DataGrid] Fix deDe localization
  packages/grid/_modules_/grid/locales/deDE.ts
Labels: bug 🐛, component: DataGrid

#1620 [docs] Add missing descriptions in `GridFilterApi`
  packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts
  packages/grid/_modules_/grid/models/api/filterApi.ts
  packages/grid/_modules_/grid/models/api/gridApi.ts
  packages/grid/_modules_/grid/models/api/gridFilterApi.ts
Labels: component: DataGrid, docs

#1628 [DataGrid] Pass state values as props
  packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderFilterIcon.tsx
  packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderMenuIcon.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeadersItemCollection.tsx
Labels: bug 🐛, component: DataGrid

#1622 [docs] Reshuffle columns and rows styling sections
  docs/src/pages/components/data-grid/columns/columns.md
  docs/src/pages/components/data-grid/rows/rows.md
  docs/src/pages/components/data-grid/style/StylingCellsGrid.js
  docs/src/pages/components/data-grid/style/StylingCellsGrid.tsx
  docs/src/pages/components/data-grid/style/StylingHeaderGrid.js
  docs/src/pages/components/data-grid/style/StylingHeaderGrid.tsx
  docs/src/pages/components/data-grid/style/StylingRowsGrid.js
  docs/src/pages/components/data-grid/style/StylingRowsGrid.tsx
  docs/src/pages/components/data-grid/style/style.md
Labels: component: DataGrid, docs

#1586 [core] Replace `classnames` utility with `clsx` dependency
  packages/grid/_modules_/grid/components/GridRow.tsx
  packages/grid/_modules_/grid/components/GridRowCount.tsx
  packages/grid/_modules_/grid/components/GridScrollArea.tsx
  packages/grid/_modules_/grid/components/GridSelectedRowCount.tsx
  packages/grid/_modules_/grid/components/cell/GridCell.tsx
  packages/grid/_modules_/grid/components/cell/GridEditBooleanCell.tsx
  packages/grid/_modules_/grid/components/cell/GridRowCells.tsx
  packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderMenuIcon.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderSeparator.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderTitle.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaders.tsx
  packages/grid/_modules_/grid/components/containers/GridColumnsContainer.tsx
  packages/grid/_modules_/grid/components/containers/GridDataContainer.tsx
  packages/grid/_modules_/grid/components/containers/GridFooterContainer.tsx
  packages/grid/_modules_/grid/components/containers/GridOverlay.tsx
  packages/grid/_modules_/grid/components/containers/GridRoot.tsx
  packages/grid/_modules_/grid/components/containers/GridToolbarContainer.tsx
  packages/grid/_modules_/grid/components/containers/GridWindow.tsx
  packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnMenu.tsx
  packages/grid/_modules_/grid/components/panel/GridPanelContent.tsx
  packages/grid/_modules_/grid/components/panel/GridPanelFooter.tsx
  packages/grid/_modules_/grid/components/panel/GridPanelHeader.tsx
  packages/grid/_modules_/grid/components/panel/GridPanelWrapper.tsx
  packages/grid/_modules_/grid/utils/classnames.ts
  packages/grid/_modules_/grid/utils/index.ts
  packages/grid/_modules_/grid/utils/utils.ts
  packages/grid/data-grid/package.json
  packages/grid/data-grid/src/DataGrid.tsx
  packages/grid/x-grid/package.json
  packages/grid/x-grid/src/XGrid.tsx
Labels: core

#1460 [DataGrid] Fix `id` and `aria-labelledby` attributes on the column menu
  packages/grid/_modules_/grid/GridComponent.tsx
  packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderMenuIcon.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx
  packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnHeaderMenu.tsx
  packages/grid/_modules_/grid/hooks/features/columnMenu/columnMenuState.ts
  packages/grid/_modules_/grid/hooks/features/columnMenu/useGridColumnMenu.ts
  packages/grid/_modules_/grid/models/api/columnMenuApi.ts
  packages/grid/x-grid/src/tests/columns.XGrid.test.tsx
Labels: bug 🐛, component: DataGrid

#1415 [DataGrid] Add sort icon for when column is unsorted
  docs/pages/api-docs/data-grid.md
  docs/pages/api-docs/x-grid.md
  docs/src/pages/components/data-grid/overview/DataGridDemo.js
  docs/src/pages/components/data-grid/overview/DataGridDemo.tsx
  packages/grid/_modules_/grid/components/columnHeaders/ColumnHeaderFilterIcon.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderSortIcon.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnUnsortedIcon.tsx
  packages/grid/_modules_/grid/components/containers/GridRootStyles.ts
  packages/grid/_modules_/grid/hooks/features/useGridComponents.tsx
  packages/grid/_modules_/grid/models/gridIconSlotsComponent.ts
  packages/grid/_modules_/grid/models/gridSlotsComponent.ts
Labels: component: DataGrid, enhancement

#1634 [DataGrid] Add Slovak (skSK) locale
  docs/src/pages/components/data-grid/localization/localization.md
  packages/grid/_modules_/grid/locales/index.ts
  packages/grid/_modules_/grid/locales/skSK.ts
Labels: component: DataGrid, enhancement

#1382 [docs] Improve the data grid components page
  docs/scripts/formattedTSDemos.js
  docs/src/pages/components/data-grid/components/CustomColumnMenu.js
  docs/src/pages/components/data-grid/components/CustomColumnMenu.tsx
  docs/src/pages/components/data-grid/components/CustomFooter.js
  docs/src/pages/components/data-grid/components/CustomFooter.tsx
  docs/src/pages/components/data-grid/components/CustomSortIcons.js
  docs/src/pages/components/data-grid/components/CustomSortIcons.tsx
  docs/src/pages/components/data-grid/components/CustomToolbarGrid.js
  docs/src/pages/components/data-grid/components/CustomToolbarGrid.tsx
  docs/src/pages/components/data-grid/components/components.md
  packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnMenu.tsx
  packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnMenuContainer.tsx
  packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnMenuProps.tsx
  packages/grid/_modules_/grid/components/menu/columnMenu/index.ts
  packages/storybook/src/stories/playground/customize-components.stories.tsx
Labels: component: DataGrid, docs

#1666 [core] colIndex is already computed
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeadersItemCollection.tsx
Labels: core

#1662 [test] Add constraints on cell render
  packages/grid/x-grid/src/tests/sorting.XGrid.test.tsx
Labels: component: DataGrid, performance

#1652 [DataGrid] Fix incorrect date selection
  packages/grid/_modules_/grid/components/cell/GridEditInputCell.tsx
  packages/grid/_modules_/grid/utils/utils.ts
Labels: bug 🐛, component: DataGrid

#1681 [docs] Clean demos components
  docs/pages/api-docs/data-grid.md
  docs/pages/api-docs/x-grid.md
  docs/src/pages/components/data-grid/components/CustomColumnMenu.js
  docs/src/pages/components/data-grid/components/CustomColumnMenu.tsx
  docs/src/pages/components/data-grid/components/CustomFooter.js
  docs/src/pages/components/data-grid/components/CustomFooter.tsx
  docs/src/pages/components/data-grid/components/CustomSortIcons.js
  docs/src/pages/components/data-grid/components/CustomSortIcons.tsx
  docs/src/pages/components/data-grid/components/components.md
Labels: docs

#1665 [DataGrid] Fix filter with object as value and value getter
  packages/grid/_modules_/grid/models/colDef/gridBooleanOperators.ts
  packages/grid/_modules_/grid/models/colDef/gridDateOperators.ts
  packages/grid/_modules_/grid/models/colDef/gridNumericOperators.ts
  packages/grid/_modules_/grid/models/colDef/gridStringOperators.ts
  packages/grid/data-grid/src/tests/filtering.DataGrid.test.tsx
  packages/storybook/src/stories/grid-filter.stories.tsx
Labels: bug 🐛, component: DataGrid

#1667 [XGrid] Rename `apiRef` methods
  packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnHeaderMenu.tsx
  packages/grid/_modules_/grid/components/panel/GridColumnsPanel.tsx
  packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterForm.tsx
  packages/grid/_modules_/grid/hooks/features/columnResize/useGridColumnResize.tsx
  packages/grid/_modules_/grid/hooks/features/columns/useGridColumns.ts
  packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts
  packages/grid/_modules_/grid/hooks/features/rows/useGridParamsApi.ts
  packages/grid/_modules_/grid/hooks/features/rows/useGridRows.ts
  packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts
  packages/grid/_modules_/grid/hooks/features/sorting/useGridSorting.ts
  packages/grid/_modules_/grid/models/api/gridColumnApi.ts
  packages/grid/_modules_/grid/models/api/gridRowApi.ts
  packages/grid/x-grid/src/tests/events.XGrid.test.tsx
  packages/grid/x-grid/src/tests/rows.XGrid.test.tsx
Labels: breaking change

#1671 [docs] Improve Filtering page
  docs/src/pages/components/data-grid/filtering/BasicFilteringGrid.js
  docs/src/pages/components/data-grid/filtering/BasicFilteringGrid.tsx
  docs/src/pages/components/data-grid/filtering/ColumnTypeFilteringGrid.js
  docs/src/pages/components/data-grid/filtering/ColumnTypeFilteringGrid.tsx
  docs/src/pages/components/data-grid/filtering/CustomRatingOperator.js
  docs/src/pages/components/data-grid/filtering/CustomRatingOperator.tsx
  docs/src/pages/components/data-grid/filtering/FilterOperators.js
  docs/src/pages/components/data-grid/filtering/FilterOperators.tsx
  docs/src/pages/components/data-grid/filtering/filtering.md
  packages/grid/x-grid-data-generator/src/employees.columns.tsx
  packages/grid/x-grid-data-generator/src/services/random-generator.ts
Labels: component: DataGrid, docs

#1572 [docs] Add description for all events
  packages/grid/_modules_/grid/constants/eventsConstants.ts
Labels: component: DataGrid, docs

#1660 [DataGrid] Add `columnHeader`, `row` and `cell` in addition to `root` in classes prop
  docs/pages/api-docs/data-grid.md
  docs/pages/api-docs/x-grid.md
  docs/src/pages/components/data-grid/demo/FullFeaturedDemo.js
  docs/src/pages/components/data-grid/demo/FullFeaturedDemo.tsx
  docs/src/pages/components/data-grid/style/AntDesignGrid.js
  docs/src/pages/components/data-grid/style/AntDesignGrid.tsx
  packages/grid/_modules_/grid/GridComponent.tsx
  packages/grid/_modules_/grid/GridComponentProps.ts
  packages/grid/_modules_/grid/components/GridRow.tsx
  packages/grid/_modules_/grid/components/GridViewport.tsx
  packages/grid/_modules_/grid/components/cell/GridCell.tsx
  packages/grid/_modules_/grid/components/cell/GridRowCells.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderTitle.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaders.tsx
  packages/grid/_modules_/grid/components/containers/GridRootStyles.ts
  packages/grid/_modules_/grid/constants/cssClassesConstants.ts
  packages/grid/_modules_/grid/hooks/features/columnReorder/useGridColumnReorder.tsx
  packages/grid/_modules_/grid/hooks/features/columnResize/useGridColumnResize.tsx
  packages/grid/_modules_/grid/hooks/utils/useOptionsProp.ts
  packages/grid/_modules_/grid/models/colDef/gridCheckboxSelection.tsx
  packages/grid/_modules_/grid/models/gridClasses.ts
  packages/grid/_modules_/grid/models/gridOptions.tsx
  packages/grid/_modules_/grid/models/index.ts
  packages/grid/_modules_/grid/utils/domUtils.ts
  packages/grid/_modules_/grid/utils/material-ui-utils.ts
  packages/grid/_modules_/grid/utils/utils.ts
  packages/grid/data-grid/src/DataGrid.tsx
  packages/grid/data-grid/src/tests/sorting.DataGrid.test.tsx
  packages/grid/x-grid/src/XGrid.tsx
  packages/grid/x-grid/src/tests/events.XGrid.test.tsx
  packages/grid/x-grid/src/tests/sorting.XGrid.test.tsx
Labels: breaking change, component: DataGrid, enhancement

#1661 [DataGrid] Make rows immutable for better developer experience
  packages/grid/_modules_/grid/GridComponent.tsx
  packages/grid/_modules_/grid/hooks/features/rows/useGridFreezeRows.ts
  packages/grid/_modules_/grid/models/gridRows.ts
  packages/grid/data-grid/src/tests/layout.DataGrid.test.tsx
  packages/storybook/src/stories/grid-sorting.stories.tsx
Labels: bug 🐛, component: DataGrid

#1583 [DataGrid] Fix overflow of maximum page
  docs/src/pages/components/data-grid/pagination/ApiRefPaginationGrid.js
  docs/src/pages/components/data-grid/pagination/ApiRefPaginationGrid.tsx
  packages/grid/_modules_/grid/hooks/features/core/gridState.ts
  packages/grid/_modules_/grid/hooks/features/pagination/gridPaginationReducer.ts
  packages/grid/_modules_/grid/hooks/features/pagination/gridPaginationSelector.ts
  packages/grid/_modules_/grid/hooks/features/pagination/gridPaginationState.ts
  packages/grid/_modules_/grid/hooks/features/pagination/index.ts
  packages/grid/_modules_/grid/hooks/features/pagination/useGridPagination.ts
  packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts
  packages/grid/_modules_/grid/hooks/root/useGridContainerProps.ts
  packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx
Labels: bug 🐛, component: DataGrid

#1692 [test] Catch broken demos
  test/regressions/TestViewer.js
Labels: test

#1686 [DataGrid] Improve performance of width resizing
  packages/grid/_modules_/grid/hooks/utils/useResizeContainer.ts
  packages/grid/data-grid/src/tests/layout.DataGrid.test.tsx
Labels: component: DataGrid, performance

#1691 [docs] Fix docs demo
  docs/src/pages/components/data-grid/pagination/ApiRefPaginationGrid.js
  docs/src/pages/components/data-grid/pagination/ApiRefPaginationGrid.tsx
Labels: docs, important

#1694 [docs] Add missing CSS rules
  docs/pages/api-docs/data-grid.md
  docs/pages/api-docs/x-grid.md
Labels: component: DataGrid, docs

#1669 [DataGrid] Fix cell accessibility aria-colindex
  packages/grid/_modules_/grid/components/cell/GridCell.tsx
  packages/grid/_modules_/grid/utils/domUtils.ts
  packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx
  packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx
  packages/grid/data-grid/src/tests/sorting.DataGrid.test.tsx
  packages/grid/x-grid/src/tests/events.XGrid.test.tsx
  packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx
  packages/grid/x-grid/src/tests/pagination.XGrid.test.tsx
  packages/grid/x-grid/src/tests/reorder.XGrid.test.tsx
  packages/grid/x-grid/src/tests/sorting.XGrid.test.tsx
  test/utils/helperFn.ts
Labels: accessibility, bug 🐛, component: DataGrid

#1724 [DataGrid] Rename `GridToolbar` components for consistency
  docs/src/pages/components/data-grid/accessibility/DensitySelectorGrid.js
  docs/src/pages/components/data-grid/accessibility/DensitySelectorGrid.tsx
  docs/src/pages/components/data-grid/accessibility/DensitySelectorSmallGrid.js
  docs/src/pages/components/data-grid/accessibility/DensitySelectorSmallGrid.tsx
  docs/src/pages/components/data-grid/accessibility/accessibility.md
  docs/src/pages/components/data-grid/components/CustomToolbarGrid.js
  docs/src/pages/components/data-grid/components/CustomToolbarGrid.tsx
  docs/src/pages/components/data-grid/components/components.md
  packages/grid/_modules_/grid/components/toolbar/GridToolbar.tsx
  packages/grid/_modules_/grid/components/toolbar/GridToolbarColumnsButton.tsx
  packages/grid/_modules_/grid/components/toolbar/GridToolbarDensitySelector.tsx
  packages/grid/_modules_/grid/components/toolbar/GridToolbarFilterButton.tsx
  packages/grid/_modules_/grid/components/toolbar/index.ts
Labels: breaking change, component: DataGrid

#1718 [DataGrid] Improve deDe translation of "errorOverlayDefaultLabel"
  packages/grid/_modules_/grid/locales/deDE.ts
Labels: bug 🐛, component: DataGrid

#1729 [DataGrid] Fix changing rows per page size
  docs/src/pages/components/data-grid/pagination/BasicPaginationGrid.js
  docs/src/pages/components/data-grid/pagination/BasicPaginationGrid.tsx
  docs/src/pages/components/data-grid/pagination/SizePaginationGrid.js
  docs/src/pages/components/data-grid/pagination/SizePaginationGrid.tsx
  packages/grid/_modules_/grid/hooks/features/pagination/useGridPagination.ts
Labels: bug 🐛, component: DataGrid, docs

#1754 [core] Help support different documents
  packages/grid/_modules_/grid/components/cell/GridCell.tsx
  packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboard.ts
Labels: core

#1753 [test] Reduce flakiness
  packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx
Labels: test

#1752 [docs] Fix 404 link
  docs/src/pages/components/data-grid/pagination/pagination.md
Labels: component: DataGrid, docs

#1751 [core] Batch updates of storybook
  .github/dependabot.yml
Labels: core

#1727 [DataGrid] Replace ids with scalable values
  packages/grid/_modules_/grid/components/cell/GridEditBooleanCell.tsx
  packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterForm.tsx
  packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterInputValue.tsx
Labels: accessibility

#1716 [DataGrid] Remove `cellClassRules` from `GridColDef`
  docs/src/pages/components/data-grid/style/StylingCellsGrid.js
  docs/src/pages/components/data-grid/style/StylingCellsGrid.tsx
  packages/grid/_modules_/grid/components/cell/GridCell.tsx
  packages/grid/_modules_/grid/components/cell/GridRowCells.tsx
  packages/grid/_modules_/grid/models/colDef/gridColDef.ts
  packages/grid/_modules_/grid/models/gridCellClass.ts
  packages/storybook/src/stories/grid-error.stories.tsx
  packages/storybook/src/stories/grid-style.stories.tsx
  packages/storybook/src/stories/playground/customize-components.stories.tsx
Labels: breaking change

#1719 [DataGrid] Fix `onPageChange` doesn't update the `page` when a pagination button is clicked
  packages/grid/_modules_/grid/components/GridPagination.tsx
  packages/grid/_modules_/grid/constants/eventsConstants.ts
  packages/grid/_modules_/grid/hooks/features/pagination/useGridPagination.ts
  packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx
Labels: bug 🐛, component: DataGrid

#1767 [docs] Update `GridApi` descriptions
  packages/grid/_modules_/grid/hooks/features/localeText/useLocaleText.tsx
  packages/grid/_modules_/grid/hooks/features/rows/useGridEditRows.ts
  packages/grid/_modules_/grid/models/api/columnMenuApi.ts
  packages/grid/_modules_/grid/models/api/gridApi.ts
  packages/grid/_modules_/grid/models/api/gridColumnApi.ts
  packages/grid/_modules_/grid/models/api/gridColumnMenuApi.ts
  packages/grid/_modules_/grid/models/api/gridCoreApi.ts
  packages/grid/_modules_/grid/models/api/gridCsvExportApi.ts
  packages/grid/_modules_/grid/models/api/gridDensityApi.ts
  packages/grid/_modules_/grid/models/api/gridEditRowApi.ts
  packages/grid/_modules_/grid/models/api/gridEventsApi.ts
  packages/grid/_modules_/grid/models/api/gridFilterApi.ts
  packages/grid/_modules_/grid/models/api/gridFocusApi.ts
  packages/grid/_modules_/grid/models/api/gridLocaleTextApi.ts
  packages/grid/_modules_/grid/models/api/gridPaginationApi.ts
  packages/grid/_modules_/grid/models/api/gridParamsApi.ts
  packages/grid/_modules_/grid/models/api/gridPreferencesPanelApi.ts
  packages/grid/_modules_/grid/models/api/gridRowApi.ts
  packages/grid/_modules_/grid/models/api/gridSelectionApi.ts
  packages/grid/_modules_/grid/models/api/gridSortApi.ts
  packages/grid/_modules_/grid/models/api/gridStateApi.ts
  packages/grid/_modules_/grid/models/api/gridVirtualizationApi.ts
  packages/grid/_modules_/grid/models/api/preferencesPanelApi.ts
Labels: breaking change, docs

#1763 [DataGrid] Increase the minimum version of core v5 supported
  packages/grid/data-grid/README.md
  packages/grid/data-grid/package.json
  packages/grid/x-grid-data-generator/package.json
  packages/grid/x-grid/README.md
  packages/grid/x-grid/package.json
Labels: bug 🐛, component: DataGrid

#1764 [DataGrid] Add customisable `aria-label`, `aria-labelledby` field
  docs/pages/api-docs/data-grid.md
  docs/pages/api-docs/x-grid.md
  packages/grid/_modules_/grid/GridComponent.tsx
  packages/grid/_modules_/grid/GridComponentProps.ts
  packages/grid/_modules_/grid/components/containers/GridRoot.tsx
  packages/grid/_modules_/grid/constants/localeTextConstants.ts
  packages/grid/_modules_/grid/locales/bgBG.ts
  packages/grid/_modules_/grid/locales/deDE.ts
  packages/grid/_modules_/grid/locales/elGR.ts
  packages/grid/_modules_/grid/locales/esES.ts
  packages/grid/_modules_/grid/locales/frFR.ts
  packages/grid/_modules_/grid/locales/jaJP.ts
  packages/grid/_modules_/grid/locales/nlNL.ts
  packages/grid/_modules_/grid/locales/plPL.ts
  packages/grid/_modules_/grid/locales/ptBR.ts
  packages/grid/_modules_/grid/locales/skSK.ts
  packages/grid/_modules_/grid/locales/trTR.ts
  packages/grid/_modules_/grid/locales/ukUA.ts
  packages/grid/_modules_/grid/models/api/gridLocaleTextApi.ts
Labels: accessibility, component: DataGrid

#1706 [XGrid] Fix onFilterModelChange not firing
  packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts
  packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx
Labels: bug 🐛, components: XGrid

#1750 [docs] Improve Custom edit component demo
  docs/src/pages/components/data-grid/editing/RenderRatingEditCellGrid.js
  docs/src/pages/components/data-grid/editing/RenderRatingEditCellGrid.tsx
Labels: component: DataGrid, docs

#1731 [DataGrid] Undefined issue fix
  docs/src/pages/components/data-grid/columns/columns.md
  docs/src/pages/components/data-grid/style/style.md
Labels: bug 🐛, component: DataGrid, docs

#1774 [docs] Remove redundant customizable pagination section
  docs/src/pages/components/data-grid/components/components.md
  docs/src/pages/components/data-grid/pagination/pagination.md
  packages/grid/_modules_/grid/hooks/utils/useResizeContainer.ts
Labels: component: DataGrid, docs

#1778 [DataGrid] Improve `headerClassName` type
  docs/src/pages/components/data-grid/style/style.md
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx
  packages/grid/_modules_/grid/models/colDef/gridColDef.ts
  packages/grid/_modules_/grid/models/gridCellClass.ts
  packages/grid/_modules_/grid/models/gridColumnHeaderClass.ts
  packages/grid/_modules_/grid/models/index.ts
  packages/grid/data-grid/src/tests/cells.DataGrid.test.tsx
  packages/grid/data-grid/src/tests/columnHeaders.DataGrid.test.tsx
  packages/storybook/src/stories/grid-style.stories.tsx
  packages/storybook/src/stories/playground/customize-components.stories.tsx
Labels: breaking change, enhancement
