Repository mui/mui-x, pull requests merged in 2021-07, with the labels that each got.

#2003 [docs] Fix description of union types
  docs/pages/api-docs/data-grid/grid-api.md
  docs/scripts/buildApi.ts
Labels: bug 🐛, docs

#1967 [DataGrid] Rename onColumnResizeCommitted to onColumnWidthChange
  docs/pages/api-docs/data-grid/data-grid.md
  docs/pages/api-docs/data-grid/x-grid.md
  docs/src/pages/components/data-grid/columns/columns.md
  docs/src/pages/components/data-grid/events/events.json
  packages/grid/_modules_/grid/constants/eventsConstants.ts
  packages/grid/_modules_/grid/hooks/features/columnResize/useGridColumnResize.tsx
  packages/grid/_modules_/grid/models/gridOptions.tsx
Labels: breaking change, component: DataGrid, enhancement

#1998 [XGrid] Add option to select only visible rows on the current page
  docs/pages/api-docs/data-grid/x-grid.md
  packages/grid/_modules_/grid/components/columnSelection/GridHeaderCheckbox.tsx
  packages/grid/_modules_/grid/hooks/features/pagination/gridPaginationSelector.ts
  packages/grid/_modules_/grid/models/gridOptions.tsx
  packages/grid/data-grid/src/DataGrid.tsx
  packages/grid/data-grid/src/tests/selection.DataGrid.test.tsx
  packages/grid/x-grid/src/tests/selection.XGrid.test.tsx
Labels: components: XGrid, enhancement

#1956 [DataGrid] Add single select column type
  docs/pages/api-docs/data-grid/grid-col-def.md
  docs/src/pages/components/data-grid/columns/ColumnTypesGrid.js
  docs/src/pages/components/data-grid/columns/ColumnTypesGrid.tsx
  docs/src/pages/components/data-grid/columns/columns.md
  docs/src/pages/components/data-grid/demo/FullFeaturedDemo.js
  docs/src/pages/components/data-grid/demo/FullFeaturedDemo.tsx
  packages/grid/_modules_/grid/components/cell/GridEditSingleSelectCell.tsx
  packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterInputValue.tsx
  packages/grid/_modules_/grid/models/colDef/gridColDef.ts
  packages/grid/_modules_/grid/models/colDef/gridColType.ts
  packages/grid/_modules_/grid/models/colDef/gridDefaultColumnTypes.ts
  packages/grid/_modules_/grid/models/colDef/gridSingleSelectColDef.tsx
  packages/grid/_modules_/grid/models/colDef/gridSingleSelectOperators.ts
  packages/grid/data-grid/src/tests/filtering.DataGrid.test.tsx
  packages/grid/x-grid-data-generator/src/commodities.columns.tsx
  packages/grid/x-grid-data-generator/src/employees.columns.tsx
  packages/grid/x-grid-data-generator/src/renderer/index.ts
  packages/grid/x-grid-data-generator/src/renderer/renderEditContractType.tsx
  packages/grid/x-grid-data-generator/src/renderer/renderEditRateType.tsx
  packages/grid/x-grid-data-generator/src/renderer/renderEditTaxCode.tsx
  packages/grid/x-grid-data-generator/src/services/static-data.ts
  packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx
  packages/storybook/src/stories/grid-columns.stories.tsx
Labels: component: DataGrid, enhancement

#1964 [DataGrid] Fix scrollToIndexes offscreen column
  packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualColumns.ts
  packages/grid/x-grid/src/tests/rows.XGrid.test.tsx
Labels: bug 🐛, component: DataGrid

#1996 [core] Remove unused event 'cellFocusChange'
  packages/grid/_modules_/grid/hooks/features/focus/useGridFocus.ts
Labels: component: DataGrid, core

#2015 [core] Use find instead of filter when possible
  packages/grid/x-grid-data-generator/src/commodities.columns.tsx
  packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx
  packages/storybook/src/stories/grid-columns.stories.tsx
Labels: core

#2012 [core] Add @material-ui/lab as peer dependency
  packages/grid/x-grid-data-generator/package.json
Labels: core

#1995 [DataGrid] Remove focus on cell when its row is removed from the data
  packages/grid/_modules_/grid/hooks/features/focus/useGridFocus.ts
  packages/grid/_modules_/grid/useGridComponent.tsx
  packages/grid/x-grid/src/tests/rows.XGrid.test.tsx
Labels: bug 🐛, component: DataGrid

#1997 [DataGrid] Add "is empty" and "is not empty" operators
  packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterForm.tsx
  packages/grid/_modules_/grid/constants/localeTextConstants.ts
  packages/grid/_modules_/grid/hooks/features/filter/gridFilterSelector.ts
  packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts
  packages/grid/_modules_/grid/locales/bgBG.ts
  packages/grid/_modules_/grid/locales/csCZ.ts
  packages/grid/_modules_/grid/locales/deDE.ts
  packages/grid/_modules_/grid/locales/elGR.ts
  packages/grid/_modules_/grid/locales/esES.ts
  packages/grid/_modules_/grid/locales/frFR.ts
  packages/grid/_modules_/grid/locales/itIT.ts
  packages/grid/_modules_/grid/locales/jaJP.ts
  packages/grid/_modules_/grid/locales/nlNL.ts
  packages/grid/_modules_/grid/locales/plPL.ts
  packages/grid/_modules_/grid/locales/ptBR.ts
  packages/grid/_modules_/grid/locales/ruRU.ts
  packages/grid/_modules_/grid/locales/skSK.ts
  packages/grid/_modules_/grid/locales/trTR.ts
  packages/grid/_modules_/grid/locales/ukUA.ts
  packages/grid/_modules_/grid/models/colDef/gridBooleanOperators.ts
  packages/grid/_modules_/grid/models/colDef/gridDateOperators.ts
  packages/grid/_modules_/grid/models/colDef/gridNumericOperators.ts
  packages/grid/_modules_/grid/models/colDef/gridStringOperators.ts
  packages/grid/_modules_/grid/models/gridFilterOperator.ts
  packages/grid/data-grid/src/tests/filtering.DataGrid.test.tsx
  packages/storybook/src/stories/grid-filter.stories.tsx
Labels: component: DataGrid, enhancement

#2075 [core] Configure Renovate and remove Dependabot
  .github/dependabot.yml
  renovate.json
Labels: core

#1823 [DataGrid] Implement useControlState hook, and add control state on selectionModel
  docs/pages/api-docs/data-grid/data-grid.md
  docs/pages/api-docs/data-grid/x-grid.md
  docs/src/pages/components/data-grid/events/events.json
  docs/src/pages/components/data-grid/selection/ControlledSelectionGrid.js
  docs/src/pages/components/data-grid/selection/ControlledSelectionGrid.tsx
  packages/grid/_modules_/grid/components/GridViewport.tsx
  packages/grid/_modules_/grid/constants/eventsConstants.ts
  packages/grid/_modules_/grid/hooks/features/clipboard/useGridClipboard.ts
  packages/grid/_modules_/grid/hooks/features/core/gridState.ts
  packages/grid/_modules_/grid/hooks/features/core/index.ts
  packages/grid/_modules_/grid/hooks/features/core/useGridControlState.ts
  packages/grid/_modules_/grid/hooks/features/core/useGridState.ts
  packages/grid/_modules_/grid/hooks/features/export/serializers/csvSerializer.ts
  packages/grid/_modules_/grid/hooks/features/export/useGridCsvExport.tsx
  packages/grid/_modules_/grid/hooks/features/selection/gridSelectionSelector.ts
  packages/grid/_modules_/grid/hooks/features/selection/gridSelectionState.ts
  packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts
  packages/grid/_modules_/grid/hooks/root/useGridApiMethod.ts
  packages/grid/_modules_/grid/models/api/gridApi.ts
  packages/grid/_modules_/grid/models/api/gridControlStateApi.ts
  packages/grid/_modules_/grid/models/api/index.ts
  packages/grid/_modules_/grid/models/colDef/gridCheckboxSelection.tsx
  packages/grid/_modules_/grid/models/controlStateItem.ts
  packages/grid/_modules_/grid/models/gridOptions.tsx
  packages/grid/_modules_/grid/models/index.ts
  packages/grid/_modules_/grid/models/params/gridRowSelectedParams.ts
  packages/grid/_modules_/grid/models/params/index.ts
  packages/grid/_modules_/grid/useGridComponent.tsx
  packages/grid/data-grid/src/DataGrid.tsx
  packages/grid/data-grid/src/tests/selection.DataGrid.test.tsx
  packages/grid/x-grid/src/tests/events.XGrid.test.tsx
  packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx
  packages/grid/x-grid/src/tests/selection.XGrid.test.tsx
  packages/storybook/src/stories/grid-events.stories.tsx
  packages/storybook/src/stories/grid-selection.stories.tsx
  packages/storybook/src/stories/grid-streaming.stories.tsx
Labels: breaking change

#2010 [DataGrid] apiRef.current.getRow can return null
  docs/pages/api-docs/data-grid/grid-api.md
  packages/grid/_modules_/grid/hooks/features/rows/useGridParamsApi.ts
  packages/grid/_modules_/grid/hooks/features/rows/useGridRows.ts
  packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts
  packages/grid/_modules_/grid/models/api/gridRowApi.ts
  packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx
  packages/grid/x-grid/src/tests/selection.XGrid.test.tsx
Labels: component: DataGrid, typescript

#1991 [docs] Add new cursor-based pagination paragraph
  docs/src/pages/components/data-grid/pagination/CursorPaginationGrid.js
  docs/src/pages/components/data-grid/pagination/CursorPaginationGrid.tsx
  docs/src/pages/components/data-grid/pagination/pagination.md
Labels: component: DataGrid, docs

#2060 [core] Remove styled-components
  package.json
  packages/storybook/package.json
  yarn.lock
Labels: core

#2036 [docs] Better explain what happens in the future
  docs/src/pages/components/data-grid/getting-started/getting-started.md
Labels: docs

#2088 [core] Remove dead code
  packages/grid/x-grid/src/tests/reorder.XGrid.test.tsx
Labels: test

#1989 [XGrid] Close column header menu when resizing column
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderSeparator.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeadersItemCollection.tsx
  packages/grid/_modules_/grid/hooks/features/columnMenu/useGridColumnMenu.ts
  packages/grid/x-grid/src/tests/columnHeaders.XGrid.test.tsx
Labels: bug 🐛, components: XGrid

#2008 [DataGrid] Allow to customize the columns exported as CSV
  docs/pages/api-docs/data-grid/grid-col-def.md
  docs/src/pages/components/data-grid/export/export.md
  packages/grid/_modules_/grid/hooks/features/export/useGridCsvExport.tsx
  packages/grid/_modules_/grid/models/colDef/gridColDef.ts
  packages/grid/_modules_/grid/models/gridExport.ts
  packages/grid/x-grid/src/tests/export.XGrid.test.tsx
Labels: component: DataGrid, enhancement

#2051 [DataGrid] Fix manual entry in date fields
  packages/grid/_modules_/grid/components/cell/GridEditDateCell.tsx
  packages/grid/_modules_/grid/components/cell/GridEditInputCell.tsx
  packages/grid/_modules_/grid/models/colDef/gridDateColDef.ts
  packages/grid/_modules_/grid/utils/utils.ts
  packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx
Labels: bug 🐛, component: DataGrid

#1966 [DataGrid] Emit `onSelectionModelChange` when selection state changes
  packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts
  packages/grid/x-grid/src/tests/selection.XGrid.test.tsx
Labels: bug 🐛, component: DataGrid

#2091 [XGrid] Column sorting in GridPanel is experimental
  packages/grid/_modules_/grid/components/panel/GridColumnsPanel.tsx
Labels: bug 🐛, components: XGrid

#2093 [core] Use getColumnHeaderCell in tests
  packages/grid/data-grid/src/tests/layout.DataGrid.test.tsx
Labels: core, test

#2089 [XGrid] Fix column resize on touch devices
  packages/grid/_modules_/grid/hooks/features/columnResize/useGridColumnResize.tsx
  packages/grid/x-grid/src/tests/columnHeaders.XGrid.test.tsx
  packages/grid/x-grid/src/tests/columns.XGrid.test.tsx
Labels: components: XGrid, regression :rabbit2:

#2086 [core] Renovate : Group storybook updates
  renovate.json
Labels: core, dependencies

#1986 [DataGrid] Emit `GRID_PAGE_SIZE_CHANGE` when autoPageSize is set and the grid size changes
  packages/grid/_modules_/grid/hooks/features/pagination/useGridPagination.ts
  packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx
  test/utils/helperFn.ts
Labels: component: DataGrid

#2033 [DataGrid] Fix crash when id has a single-quote
  packages/grid/_modules_/grid/utils/domUtils.ts
  packages/grid/x-grid/src/tests/rows.XGrid.test.tsx
Labels: bug 🐛, component: DataGrid

#2084 [DataGrid] Make GridToolbarXXX props overridable
  packages/grid/_modules_/grid/components/toolbar/GridToolbarColumnsButton.tsx
  packages/grid/_modules_/grid/components/toolbar/GridToolbarDensitySelector.tsx
  packages/grid/_modules_/grid/components/toolbar/GridToolbarExport.tsx
  packages/grid/_modules_/grid/components/toolbar/GridToolbarFilterButton.tsx
Labels: bug 🐛, component: DataGrid

#2114 [core] Upgrade dependencies
  docs/scripts/buildApi.ts
  yarn.lock
Labels: core

#2034 [DataGrid] Remove 'hide: true' from a column should correctly resize the others column
  packages/grid/_modules_/grid/hooks/features/columns/useGridColumns.ts
  packages/grid/data-grid/src/tests/layout.DataGrid.test.tsx
Labels: bug 🐛, component: DataGrid

#2115 [core] Remove implicit :scope
  packages/grid/_modules_/grid/utils/domUtils.ts
Labels: core

#2116 [DataGrid] Support style prop
  packages/grid/_modules_/grid/GridComponentProps.ts
  packages/grid/_modules_/grid/components/containers/GridRoot.tsx
  packages/grid/x-grid/src/tests/layout.XGrid.test.tsx
Labels: component: DataGrid, enhancement

#2092 [core] Fix missing git source in packages
  packages/grid/data-grid/package.json
  packages/grid/x-grid-data-generator/package.json
  packages/grid/x-grid/package.json
  packages/storybook/package.json
  packages/x-license/package.json
Labels: core

#1994 [DataGrid] Allow passing styles and Popper props to GridPanel
  packages/grid/_modules_/grid/components/panel/GridPanel.spec.tsx
  packages/grid/_modules_/grid/components/panel/GridPanel.test.tsx
  packages/grid/_modules_/grid/components/panel/GridPanel.tsx
  packages/grid/_modules_/grid/utils/material-ui-utils.ts
Labels: bug 🐛, component: DataGrid

#2118 [DataGrid] Add missing localeText types
  packages/grid/_modules_/grid/models/api/gridLocaleTextApi.ts
Labels: bug 🐛, typescript

#2087 [test] Test the validation before saving a value
  docs/pages/api-docs/data-grid/grid-api.md
  docs/src/pages/components/data-grid/editing/RenderRatingEditCellGrid.js
  docs/src/pages/components/data-grid/editing/RenderRatingEditCellGrid.tsx
  packages/grid/_modules_/grid/components/cell/GridEditBooleanCell.tsx
  packages/grid/_modules_/grid/components/cell/GridEditDateCell.tsx
  packages/grid/_modules_/grid/components/cell/GridEditInputCell.tsx
  packages/grid/_modules_/grid/components/cell/GridEditSingleSelectCell.tsx
  packages/grid/_modules_/grid/hooks/features/rows/useGridEditRows.ts
  packages/grid/_modules_/grid/models/api/gridEditRowApi.ts
  packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx
Labels: component: DataGrid, test

#2140 [core] Copy getClasses from the core (removed in v5)
  packages/grid/_modules_/grid/components/panel/GridPanel.test.tsx
  packages/grid/_modules_/grid/components/panel/GridPanel.tsx
  packages/grid/_modules_/grid/utils/material-ui-utils.ts
Labels: core, test

#2152 [test] Allow tests to run for up to 5 instead of 4 seconds
  test/karma.conf.js
Labels: test

#2117 [DataGrid] Fix localeText type
  docs/pages/api-docs/data-grid/grid-api.md
  packages/grid/_modules_/grid/models/api/gridLocaleTextApi.ts
  packages/grid/data-grid/src/tests/DataGrid.spec.tsx
Labels: bug 🐛, typescript

#2108 [DataGrid] Fix support for `@material-ui/core@4.12`
  packages/grid/_modules_/grid/components/GridPagination.tsx
  packages/grid/_modules_/grid/components/panel/GridPanel.tsx
  packages/grid/_modules_/grid/utils/getGridLocalization.ts
  packages/grid/_modules_/grid/utils/utils.ts
  yarn.lock
Labels: bug 🐛, component: DataGrid, important

#2155 [DataGrid] Use Intl.Collator for string comparison
  packages/grid/_modules_/grid/models/colDef/gridStringOperators.ts
  packages/grid/_modules_/grid/utils/sortingUtils.ts
Labels: component: DataGrid, enhancement, performance

#2160 [docs] Fix broken env
  yarn.lock
Labels: docs

#2130 [core] Correctly test column visibility switch impact on column width
  packages/grid/data-grid/src/tests/layout.DataGrid.test.tsx
  packages/grid/x-grid/src/tests/layout.XGrid.test.tsx
  packages/grid/x-grid/src/tests/rows.XGrid.test.tsx
Labels: core

#2166 [core] Support `docs:api` script in Windows OS
  package.json
Labels: core

#2139 [core] Use props instead of options for event handler
  packages/grid/_modules_/grid/hooks/features/columnResize/useGridColumnResize.tsx
  packages/grid/_modules_/grid/hooks/features/columns/useGridColumns.ts
  packages/grid/_modules_/grid/hooks/features/infiniteLoader/useGridInfiniteLoader.ts
  packages/grid/_modules_/grid/hooks/features/rows/useGridEditRows.ts
  packages/grid/_modules_/grid/hooks/features/sorting/useGridSorting.ts
  packages/grid/_modules_/grid/hooks/root/useEvents.ts
  packages/grid/_modules_/grid/hooks/utils/useResizeContainer.ts
  packages/grid/_modules_/grid/useGridComponent.tsx
Labels: core

#1909 [DataGrid] Improve controllable filter
  docs/pages/api-docs/data-grid/data-grid.md
  docs/pages/api-docs/data-grid/x-grid.md
  docs/src/pages/components/data-grid/events/events.json
  docs/src/pages/components/data-grid/filtering/CustomRatingOperator.js
  docs/src/pages/components/data-grid/filtering/CustomRatingOperator.tsx
  docs/src/pages/components/data-grid/filtering/ExtendNumericOperator.js
  docs/src/pages/components/data-grid/filtering/ExtendNumericOperator.tsx
  docs/src/pages/components/data-grid/filtering/MultiFilteringGrid.js
  docs/src/pages/components/data-grid/filtering/MultiFilteringGrid.tsx
  docs/src/pages/components/data-grid/filtering/MultiFilteringWithOrGrid.js
  docs/src/pages/components/data-grid/filtering/MultiFilteringWithOrGrid.tsx
  docs/src/pages/components/data-grid/filtering/ServerFilterGrid.js
  docs/src/pages/components/data-grid/filtering/ServerFilterGrid.tsx
  packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterPanel.tsx
  packages/grid/_modules_/grid/constants/eventsConstants.ts
  packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts
  packages/grid/_modules_/grid/models/gridFilterItem.ts
  packages/grid/_modules_/grid/models/gridOptions.tsx
  packages/grid/_modules_/grid/models/params/gridFilterModelParams.ts
  packages/grid/_modules_/grid/models/params/index.ts
  packages/grid/data-grid/src/DataGrid.tsx
  packages/grid/data-grid/src/tests/filtering.DataGrid.test.tsx
  packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx
  packages/storybook/src/stories/grid-filter.stories.tsx
Labels: breaking change, component: DataGrid

#2095 [DataGrid] Improve controllable sorting
  docs/pages/api-docs/data-grid/data-grid.md
  docs/pages/api-docs/data-grid/x-grid.md
  docs/src/pages/components/data-grid/sorting/BasicSortingGrid.js
  docs/src/pages/components/data-grid/sorting/BasicSortingGrid.tsx
  docs/src/pages/components/data-grid/sorting/ComparatorSortingGrid.js
  docs/src/pages/components/data-grid/sorting/ComparatorSortingGrid.tsx
  docs/src/pages/components/data-grid/sorting/MultiSortingGrid.js
  docs/src/pages/components/data-grid/sorting/MultiSortingGrid.tsx
  docs/src/pages/components/data-grid/sorting/OrderSortingGrid.js
  docs/src/pages/components/data-grid/sorting/OrderSortingGrid.tsx
  docs/src/pages/components/data-grid/sorting/ServerSortingGrid.js
  docs/src/pages/components/data-grid/sorting/ServerSortingGrid.tsx
  packages/grid/_modules_/grid/hooks/features/sorting/useGridSorting.ts
  packages/grid/_modules_/grid/models/gridOptions.tsx
  packages/grid/x-grid-data-generator/src/useDemoData.ts
  packages/grid/x-grid/src/tests/sorting.XGrid.test.tsx
  packages/storybook/src/stories/grid-sorting.stories.tsx
Labels: breaking change, component: DataGrid

#2101 [DataGrid] Add `minWidth` to `GridColDef`
  docs/pages/api-docs/data-grid/grid-col-def.md
  docs/src/pages/components/data-grid/columns/ColumnFluidWidthGrid.js
  docs/src/pages/components/data-grid/columns/ColumnFluidWidthGrid.tsx
  docs/src/pages/components/data-grid/columns/ColumnMinWidthGrid.js
  docs/src/pages/components/data-grid/columns/ColumnMinWidthGrid.tsx
  docs/src/pages/components/data-grid/columns/ColumnSizingGrid.js
  docs/src/pages/components/data-grid/columns/ColumnSizingGrid.tsx
  docs/src/pages/components/data-grid/columns/columns.md
  packages/grid/_modules_/grid/hooks/features/columnResize/useGridColumnResize.tsx
  packages/grid/_modules_/grid/hooks/features/columns/useGridColumns.ts
  packages/grid/_modules_/grid/models/colDef/gridCheckboxSelection.tsx
  packages/grid/_modules_/grid/models/colDef/gridColDef.ts
  packages/grid/_modules_/grid/models/colDef/gridStringColDef.ts
  packages/grid/data-grid/src/tests/layout.DataGrid.test.tsx
Labels: component: DataGrid, enhancement

#2171 [docs] Replace fade with muiStyleAlpha
  packages/grid/x-grid-data-generator/src/renderer/renderEditProgress.tsx
Labels: bug 🐛, docs

#2162 [DataGrid] Fix scrollToIndexes behavior
  docs/pages/api-docs/data-grid/grid-api.md
  packages/grid/_modules_/grid/components/containers/GridRootStyles.ts
  packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualColumns.ts
  packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts
  packages/grid/_modules_/grid/models/api/gridVirtualizationApi.ts
  packages/grid/x-grid/src/tests/rows.XGrid.test.tsx
Labels: breaking change, bug 🐛, component: DataGrid

#2154 [XGrid] Prevent headers from scrolling during reordering
  packages/grid/_modules_/grid/constants/eventsConstants.ts
  packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts
Labels: bug 🐛, components: XGrid, regression :rabbit2:

#2169 [docs] Fix small typos in the documentation
  docs/src/pages/components/data-grid/getting-started/getting-started.md
Labels: docs

#2173 [DataGrid] Remove unused `editMode` prop
  packages/grid/_modules_/grid/models/gridOptions.tsx
  packages/storybook/src/stories/grid-rows.stories.tsx
Labels: component: DataGrid, core

#2141 [DataGrid] Remove stateId argument from GridApi getState method
  docs/pages/api-docs/data-grid/grid-api.md
  packages/grid/_modules_/grid/hooks/features/core/useGridApi.ts
  packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts
  packages/grid/_modules_/grid/hooks/features/pagination/useGridPagination.ts
  packages/grid/_modules_/grid/models/api/gridStateApi.ts
Labels: breaking change, component: DataGrid, core, typescript

#2085 [XGrid] Add ability to disable reorder on some columns
  docs/pages/api-docs/data-grid/grid-col-def.md
  docs/src/pages/components/data-grid/columns/ColumnOrderingDisabledGrid.js
  docs/src/pages/components/data-grid/columns/ColumnOrderingDisabledGrid.tsx
  docs/src/pages/components/data-grid/columns/columns.md
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx
  packages/grid/_modules_/grid/hooks/features/columnReorder/useGridColumnReorder.tsx
  packages/grid/_modules_/grid/hooks/features/columns/useGridColumns.ts
  packages/grid/_modules_/grid/models/colDef/gridCheckboxSelection.tsx
  packages/grid/_modules_/grid/models/colDef/gridColDef.ts
  packages/grid/x-grid/src/tests/reorder.XGrid.test.tsx
  packages/storybook/src/stories/grid-reorder.stories.tsx
Labels: components: XGrid, enhancement

#2157 [DataGrid] Improve GridToolbarXXX props flexibility
  packages/grid/_modules_/grid/components/toolbar/GridToolbarFilterButton.tsx
Labels: component: DataGrid, enhancement

#2149 [DataGrid] Add quick filter demo
  docs/src/pages/components/data-grid/filtering/QuickFilteringGrid.js
  docs/src/pages/components/data-grid/filtering/QuickFilteringGrid.tsx
  docs/src/pages/components/data-grid/filtering/filtering.md
  packages/grid/_modules_/grid/models/colDef/gridStringOperators.ts
  packages/grid/_modules_/grid/utils/utils.ts
Labels: component: DataGrid, docs

#2143 [DataGrid] Improve controllable cell edit
  docs/pages/api-docs/data-grid/data-grid.md
  docs/pages/api-docs/data-grid/grid-api.md
  docs/pages/api-docs/data-grid/x-grid.md
  docs/src/pages/components/data-grid/editing/EditRowsModelControlGrid.js
  docs/src/pages/components/data-grid/editing/EditRowsModelControlGrid.tsx
  docs/src/pages/components/data-grid/editing/ValidateCellApiRefGrid.js
  docs/src/pages/components/data-grid/editing/ValidateCellApiRefGrid.tsx
  docs/src/pages/components/data-grid/editing/ValidateRowModelControlGrid.js
  docs/src/pages/components/data-grid/editing/ValidateRowModelControlGrid.tsx
  docs/src/pages/components/data-grid/editing/ValidateServerNameGrid.js
  docs/src/pages/components/data-grid/editing/ValidateServerNameGrid.tsx
  docs/src/pages/components/data-grid/editing/ValueGetterGrid.js
  docs/src/pages/components/data-grid/editing/ValueGetterGrid.tsx
  docs/src/pages/components/data-grid/editing/editing.md
  docs/src/pages/components/data-grid/events/events.json
  packages/grid/_modules_/grid/constants/eventsConstants.ts
  packages/grid/_modules_/grid/hooks/features/rows/useGridEditRows.ts
  packages/grid/_modules_/grid/models/api/gridEditRowApi.ts
  packages/grid/_modules_/grid/models/gridOptions.tsx
  packages/grid/_modules_/grid/models/params/gridEditCellParams.ts
  packages/grid/_modules_/grid/utils/keyboardUtils.ts
  packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx
  packages/storybook/src/stories/grid-rows.stories.tsx
Labels: component: DataGrid, enhancement

#2167 [docs] Add missing API docs
  docs/pages/api-docs/data-grid/data-grid.md
  docs/pages/api-docs/data-grid/x-grid.md
  packages/grid/_modules_/grid/models/gridOptions.tsx
Labels: component: DataGrid, docs

#2102 [docs] Generate api doc for the GridExportCSVOptions interface
  docs/pages/api-docs/data-grid/grid-export-csv-options.js
  docs/pages/api-docs/data-grid/grid-export-csv-options.md
  docs/pages/api-docs/data-grid/index.md
  docs/scripts/buildApi.ts
  docs/src/pages.js
  docs/src/pages/components/data-grid/export/export.md
Labels: docs

#2112 [DataGrid] Fix support for singleSelect with numeric values
  docs/pages/api-docs/data-grid/grid-col-def.md
  packages/grid/_modules_/grid/components/cell/GridEditSingleSelectCell.tsx
  packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterInputValue.tsx
  packages/grid/_modules_/grid/models/colDef/gridColDef.ts
  packages/grid/_modules_/grid/models/colDef/gridSingleSelectOperators.ts
  packages/grid/data-grid/src/tests/filtering.DataGrid.test.tsx
  packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx
  packages/storybook/src/stories/grid-columns.stories.tsx
Labels: bug 🐛, component: DataGrid

#2200 [test] Fix singleSelect tests
  packages/grid/data-grid/src/tests/filtering.DataGrid.test.tsx
Labels: component: DataGrid, important, test

#2196 [DataGrid] Fix `disableMultipleColumnsFiltering` console warning
  packages/grid/data-grid/src/DataGrid.tsx
Labels: bug 🐛, component: DataGrid

#2197 [DataGrid] Fix `Controlled selection` console error
  packages/grid/data-grid/src/DataGrid.tsx
  packages/grid/data-grid/src/tests/selection.DataGrid.test.tsx
Labels: bug 🐛, component: DataGrid, regression :rabbit2:

#2215 [DataGrid] Fix id passed to setEditCellValue
  packages/grid/_modules_/grid/components/cell/GridEditBooleanCell.tsx
  packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx
Labels: bug 🐛, component: DataGrid, regression :rabbit2:

#2191 [test] Sync Karma config
  .circleci/config.yml
  test/karma.conf.js
Labels: test

#2194 [docs] Describe how to export custom rendered cells
  docs/pages/api-docs/data-grid/grid-csv-export-api.json
  docs/scripts/buildApi.ts
  docs/src/pages/components/data-grid/columns/columns.md
  docs/src/pages/components/data-grid/export/CsvExportApiNoSnap.js
  docs/src/pages/components/data-grid/export/export.md
Labels: component: DataGrid, docs

#2099 [DataGrid] Improve controllable pagination
  docs/pages/api-docs/data-grid/data-grid.md
  docs/pages/api-docs/data-grid/x-grid.md
  docs/src/pages/components/data-grid/events/events.json
  docs/src/pages/components/data-grid/pagination/ControlledPaginationGrid.js
  docs/src/pages/components/data-grid/pagination/ControlledPaginationGrid.tsx
  docs/src/pages/components/data-grid/pagination/CursorPaginationGrid.js
  docs/src/pages/components/data-grid/pagination/CursorPaginationGrid.tsx
  docs/src/pages/components/data-grid/pagination/ServerPaginationGrid.js
  docs/src/pages/components/data-grid/pagination/ServerPaginationGrid.tsx
  docs/src/pages/components/data-grid/pagination/SizePaginationGrid.js
  docs/src/pages/components/data-grid/pagination/SizePaginationGrid.tsx
  packages/grid/_modules_/grid/components/GridFooter.tsx
  packages/grid/_modules_/grid/components/GridPagination.tsx
  packages/grid/_modules_/grid/components/GridViewport.tsx
  packages/grid/_modules_/grid/constants/eventsConstants.ts
  packages/grid/_modules_/grid/hooks/features/core/gridState.ts
  packages/grid/_modules_/grid/hooks/features/pagination/gridPaginationSelector.ts
  packages/grid/_modules_/grid/hooks/features/pagination/gridPaginationState.ts
  packages/grid/_modules_/grid/hooks/features/pagination/index.ts
  packages/grid/_modules_/grid/hooks/features/pagination/useGridPage.ts
  packages/grid/_modules_/grid/hooks/features/pagination/useGridPageSize.ts
  packages/grid/_modules_/grid/hooks/features/pagination/useGridPagination.ts
  packages/grid/_modules_/grid/hooks/features/rows/useGridRows.ts
  packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts
  packages/grid/_modules_/grid/hooks/root/useGridContainerProps.ts
  packages/grid/_modules_/grid/hooks/utils/useGridScrollbarSizeDetector.ts
  packages/grid/_modules_/grid/models/api/gridApi.ts
  packages/grid/_modules_/grid/models/api/gridPageApi.ts
  packages/grid/_modules_/grid/models/api/gridPageSizeApi.ts
  packages/grid/_modules_/grid/models/api/gridPaginationApi.ts
  packages/grid/_modules_/grid/models/api/index.ts
  packages/grid/_modules_/grid/models/gridOptions.tsx
  packages/grid/_modules_/grid/models/params/gridPageChangeParams.ts
  packages/grid/_modules_/grid/models/params/index.ts
  packages/grid/_modules_/grid/useGridComponent.tsx
  packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx
  packages/grid/x-grid/src/tests/pagination.XGrid.test.tsx
  packages/storybook/src/data/data-service.ts
  packages/storybook/src/stories/grid-pagination.stories.tsx
Labels: breaking change, component: DataGrid

#2214 [DataGrid] Pass value to onCellEditCommit
  docs/src/pages/components/data-grid/editing/ValueGetterGrid.js
  docs/src/pages/components/data-grid/editing/ValueGetterGrid.tsx
  packages/grid/_modules_/grid/hooks/features/rows/useGridEditRows.ts
  packages/grid/_modules_/grid/models/gridOptions.tsx
  packages/grid/_modules_/grid/models/params/gridEditCellParams.ts
  packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx
  packages/storybook/src/stories/grid-rows.stories.tsx
Labels: bug 🐛, component: DataGrid, regression :rabbit2:

#2203 [DataGrid] Improve translations to the Turkish locale
  packages/grid/_modules_/grid/locales/trTR.ts
Labels: component: DataGrid

#2210 [docs] Handle generics in api doc generation
  docs/pages/api-docs/data-grid/grid-api.md
  docs/scripts/buildApi.ts
Labels: docs

#2224 [DataGrid] Fix prop-type warning with v5
  packages/grid/_modules_/grid/components/panel/GridPanelWrapper.tsx
  packages/grid/data-grid/README.md
  packages/grid/data-grid/package.json
  packages/grid/x-grid/README.md
  packages/grid/x-grid/package.json
Labels: bug 🐛, component: DataGrid

#2179 [DataGrid] Use event.defaultMuiPrevented to prevent the default behavior
  docs/pages/api-docs/data-grid/data-grid.md
  docs/pages/api-docs/data-grid/grid-api.md
  docs/pages/api-docs/data-grid/x-grid.md
  docs/src/pages/components/data-grid/editing/CatchEditingEventsGrid.tsx
  docs/src/pages/components/data-grid/editing/StartEditButtonGrid.js
  docs/src/pages/components/data-grid/editing/StartEditButtonGrid.tsx
  docs/src/pages/components/data-grid/editing/ValidateServerNameGrid.js
  docs/src/pages/components/data-grid/editing/ValidateServerNameGrid.tsx
  docs/src/pages/components/data-grid/editing/editing.md
  docs/src/pages/components/data-grid/events/DoubleClickWithCtrlToEdit.js
  docs/src/pages/components/data-grid/events/DoubleClickWithCtrlToEdit.tsx
  docs/src/pages/components/data-grid/events/events.md
  packages/grid/_modules_/grid/GridComponentProps.ts
  packages/grid/_modules_/grid/hooks/features/columnResize/useGridColumnResize.tsx
  packages/grid/_modules_/grid/hooks/features/focus/useGridFocus.ts
  packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboard.ts
  packages/grid/_modules_/grid/hooks/features/rows/useGridEditRows.ts
  packages/grid/_modules_/grid/hooks/root/useApi.ts
  packages/grid/_modules_/grid/hooks/root/useGridApiEventHandler.ts
  packages/grid/_modules_/grid/models/api/gridCoreApi.ts
  packages/grid/_modules_/grid/models/api/gridEditRowApi.ts
  packages/grid/_modules_/grid/models/gridOptions.tsx
  packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx
  packages/grid/x-grid/src/tests/events.XGrid.test.tsx
  packages/storybook/src/stories/grid-events.stories.tsx
  packages/storybook/src/stories/grid-rows.stories.tsx
Labels: breaking change, component: DataGrid, enhancement

#2229 [test] Test support for theme translations
  packages/grid/data-grid/src/tests/layout.DataGrid.test.tsx
  packages/grid/x-grid/src/tests/layout.XGrid.test.tsx
Labels: component: DataGrid, test

#2211 [core] Add tests for column resizing
  packages/grid/x-grid/src/tests/columns.XGrid.test.tsx
Labels: core, test

#2159 [DataGrid] Add minHeight to the rendering zone
  packages/grid/_modules_/grid/components/containers/GridDataContainer.tsx
  packages/grid/_modules_/grid/hooks/root/useGridContainerProps.ts
  packages/grid/data-grid/src/tests/layout.DataGrid.test.tsx
  packages/grid/x-grid/src/tests/rows.XGrid.test.tsx
Labels: bug 🐛, component: DataGrid, regression :rabbit2:

#2014 [DataGrid] Warn when pageSize is not present in rowsPerPageOptions
  packages/grid/_modules_/grid/components/GridPagination.tsx
  packages/grid/_modules_/grid/hooks/features/core/gridState.ts
  packages/grid/_modules_/grid/hooks/features/pagination/gridPaginationState.ts
  packages/grid/_modules_/grid/hooks/features/useGridComponents.tsx
  packages/grid/_modules_/grid/models/gridSlotsComponent.ts
  packages/grid/data-grid/src/tests/pagination.DataGrid.test.tsx
  packages/grid/data-grid/src/tests/selection.DataGrid.test.tsx
  packages/grid/x-grid/src/tests/pagination.XGrid.test.tsx
  packages/grid/x-grid/src/tests/rows.XGrid.test.tsx
  packages/grid/x-grid/src/tests/selection.XGrid.test.tsx
Labels: component: DataGrid, docs, enhancement

#2232 [DataGrid] Fix CSV export when selected row id is number
  packages/grid/_modules_/grid/hooks/features/export/serializers/csvSerializer.ts
  packages/grid/x-grid/src/tests/export.XGrid.test.tsx
Labels: bug 🐛, component: DataGrid

#2233 [DataGrid] Don't export the internal utils
  docs/src/pages/components/data-grid/columns/RenderExpandCellGrid.js
  docs/src/pages/components/data-grid/columns/RenderExpandCellGrid.tsx
  docs/src/pages/components/data-grid/editing/IsCellEditableGrid.js
  docs/src/pages/components/data-grid/editing/IsCellEditableGrid.tsx
  docs/src/pages/components/data-grid/editing/ValidateRowModelControlGrid.js
  docs/src/pages/components/data-grid/editing/ValidateRowModelControlGrid.tsx
  docs/src/pages/components/data-grid/editing/ValidateServerNameGrid.js
  docs/src/pages/components/data-grid/editing/ValidateServerNameGrid.tsx
  docs/src/pages/components/data-grid/filtering/QuickFilteringGrid.js
  docs/src/pages/components/data-grid/filtering/QuickFilteringGrid.tsx
  docs/src/pages/components/data-grid/style/StylingRowsGrid.js
  docs/src/pages/components/data-grid/style/StylingRowsGrid.tsx
  packages/grid/_modules_/grid/components/GridPagination.tsx
  packages/grid/_modules_/grid/components/GridRow.tsx
  packages/grid/_modules_/grid/components/cell/GridRowCells.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderTitle.tsx
  packages/grid/_modules_/grid/components/panel/GridPanel.tsx
  packages/grid/_modules_/grid/components/panel/GridPanelWrapper.tsx
  packages/grid/_modules_/grid/hooks/features/export/useGridCsvExport.tsx
  packages/grid/_modules_/grid/index.ts
  packages/grid/_modules_/grid/locales/bgBG.ts
  packages/grid/_modules_/grid/locales/csCZ.ts
  packages/grid/_modules_/grid/locales/deDE.ts
  packages/grid/_modules_/grid/locales/elGR.ts
  packages/grid/_modules_/grid/locales/enUS.ts
  packages/grid/_modules_/grid/locales/esES.ts
  packages/grid/_modules_/grid/locales/frFR.ts
  packages/grid/_modules_/grid/locales/itIT.ts
  packages/grid/_modules_/grid/locales/jaJP.ts
  packages/grid/_modules_/grid/locales/nlNL.ts
  packages/grid/_modules_/grid/locales/plPL.ts
  packages/grid/_modules_/grid/locales/ptBR.ts
  packages/grid/_modules_/grid/locales/ruRU.ts
  packages/grid/_modules_/grid/locales/skSK.ts
  packages/grid/_modules_/grid/locales/trTR.ts
  packages/grid/_modules_/grid/locales/ukUA.ts
  packages/grid/_modules_/grid/utils/getGridLocalization.ts
  packages/grid/_modules_/grid/utils/index.ts
  packages/grid/data-grid/src/DataGrid.tsx
  packages/grid/x-grid-data-generator/src/renderer/renderPnl.tsx
  packages/grid/x-grid-data-generator/src/renderer/renderTotalPrice.tsx
  packages/grid/x-grid/src/XGrid.tsx
  packages/storybook/src/stories/grid-rows.stories.tsx
  test/regressions/TestViewer.js
Labels: breaking change, component: DataGrid, core

#2240 [XGrid] Fix width issue in FilterPopup
  packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterForm.tsx
Labels: bug 🐛, component: DataGrid
