Repository mui/mui-x, pull requests merged in 2021-03, with the labels that each got.

#1138 [core] Update to the HEAD of the monorepo
  package.json
  test/utils/setup.js
  yarn.lock
Labels: core

#1139 [docs] Improve the description of the individual packages
  packages/grid/data-grid/README.md
  packages/grid/x-grid/README.md
Labels: docs

#1117 [DataGrid] Add deDE locale
  docs/src/pages/components/data-grid/localization/localization.md
  packages/grid/_modules_/grid/locales/deDE.ts
  packages/grid/_modules_/grid/locales/index.ts
Labels: component: DataGrid, enhancement

#1150 [test] Increase timeout for XGrid demo
  test/regressions/index.test.js
Labels: test

#1025 [DataGrid] Implement base foundation for editing a cell
  docs/pages/api-docs/data-grid.md
  docs/pages/api-docs/x-grid.md
  packages/grid/_modules_/grid/GridComponent.tsx
  packages/grid/_modules_/grid/components/GridCell.tsx
  packages/grid/_modules_/grid/components/GridRowCells.tsx
  packages/grid/_modules_/grid/components/containers/GridRootStyles.ts
  packages/grid/_modules_/grid/components/editCell/EditInputCell.tsx
  packages/grid/_modules_/grid/constants/eventsConstants.ts
  packages/grid/_modules_/grid/hooks/features/core/gridState.ts
  packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboard.ts
  packages/grid/_modules_/grid/hooks/features/rows/gridEditRowsSelector.ts
  packages/grid/_modules_/grid/hooks/features/rows/index.ts
  packages/grid/_modules_/grid/hooks/features/rows/useGridEditRows.ts
  packages/grid/_modules_/grid/hooks/features/rows/useGridRows.ts
  packages/grid/_modules_/grid/hooks/root/useEvents.ts
  packages/grid/_modules_/grid/models/api/gridApi.ts
  packages/grid/_modules_/grid/models/api/gridEditRowApi.ts
  packages/grid/_modules_/grid/models/api/gridRowApi.ts
  packages/grid/_modules_/grid/models/api/index.ts
  packages/grid/_modules_/grid/models/colDef/gridColDef.ts
  packages/grid/_modules_/grid/models/colDef/gridStringColDef.ts
  packages/grid/_modules_/grid/models/gridCell.ts
  packages/grid/_modules_/grid/models/gridEditRowModel.ts
  packages/grid/_modules_/grid/models/gridOptions.tsx
  packages/grid/_modules_/grid/models/gridRows.ts
  packages/grid/_modules_/grid/models/index.ts
  packages/grid/_modules_/grid/models/params/gridCellParams.ts
  packages/grid/_modules_/grid/models/params/gridEditCellParams.ts
  packages/grid/_modules_/grid/models/params/index.ts
  packages/grid/_modules_/grid/utils/domUtils.ts
  packages/grid/_modules_/grid/utils/mergeUtils.ts
  packages/grid/_modules_/grid/utils/paramsUtils.ts
  packages/grid/_modules_/grid/utils/utils.ts
  packages/grid/x-grid-data-generator/src/renderer/renderCountry.tsx
  packages/grid/x-grid/src/tests/apiRef.XGrid.test.tsx
  packages/grid/x-grid/src/tests/rows.XGrid.test.tsx
  packages/storybook/.storybook/preview.tsx
  packages/storybook/package.json
  packages/storybook/src/stories/grid-rows.stories.tsx
Labels: component: DataGrid, enhancement

#1159 [DataGrid] Fix rendering docs to solve custom pagination issue
  docs/src/pages/components/data-grid/rendering/CustomPaginationGrid.js
  docs/src/pages/components/data-grid/rendering/CustomPaginationGrid.tsx
Labels: component: DataGrid, docs

#1155 [docs] Fix typo in localization.md
  docs/src/pages/components/data-grid/localization/localization.md
Labels: docs

#1171 [core] Add build in ignore
  .eslintignore
Labels: core

#1168 [DataGrid] Improve edit cell UI
  packages/grid/_modules_/grid/components/containers/GridRootStyles.ts
  packages/storybook/src/stories/grid-rows.stories.tsx
Labels: component: DataGrid

#1154 [DataGrid] Handle special chars when doing CSV export
  packages/grid/_modules_/grid/hooks/features/export/seralizers/csvSeraliser.ts
  packages/grid/_modules_/grid/hooks/features/export/useGridCsvExport.tsx
  packages/grid/x-grid/src/tests/apiRef.XGrid.test.tsx
Labels: bug 🐛, component: DataGrid

#1146 [DataGrid] Fix scrollbar on autopageSize
  packages/grid/_modules_/grid/hooks/root/useGridContainerProps.ts
  packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx
  packages/storybook/src/stories/grid-data.stories.tsx
  packages/storybook/src/stories/grid-pagination.stories.tsx
  packages/storybook/src/style/grid-stories.css
Labels: bug 🐛, component: DataGrid

#1170 [docs] Lazy generate fake data
  docs/pages/components/data-grid/demo.js
  docs/src/pages/components/data-grid/demo/FullFeaturedDemo.js
  docs/src/pages/components/data-grid/demo/FullFeaturedDemo.tsx
  docs/src/pages/components/data-grid/filtering/CustomRatingOperator.js
  docs/src/pages/components/data-grid/filtering/CustomRatingOperator.tsx
  docs/tsconfig.json
  package.json
  packages/grid/tsconfig.build.json
  packages/grid/x-grid-data-generator/src/asyncWorker.ts
  packages/grid/x-grid-data-generator/src/services/real-data-service.ts
  packages/grid/x-grid-data-generator/src/useDemoData.ts
  packages/storybook/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: component: DataGrid, docs

#1198 [docs] Fix typo
  docs/src/pages/components/data-grid/rendering/rendering.md
Labels: docs

#1158 [DataGrid] Improve the handling of events (rm capture, add event, add new props)
  docs/pages/api-docs/data-grid.md
  docs/pages/api-docs/x-grid.md
  docs/src/pages/components/data-grid/overview/DataGridDemo.tsx
  docs/src/pages/components/data-grid/rendering/ValueFormatterGrid.tsx
  docs/src/pages/components/data-grid/rendering/ValueGetterGrid.tsx
  docs/src/pages/components/data-grid/sorting/ComparatorSortingGrid.tsx
  packages/grid/_modules_/grid/GridComponent.tsx
  packages/grid/_modules_/grid/components/GridCell.tsx
  packages/grid/_modules_/grid/components/GridEmptyCell.tsx
  packages/grid/_modules_/grid/components/GridRow.tsx
  packages/grid/_modules_/grid/components/GridRowCells.tsx
  packages/grid/_modules_/grid/components/GridViewport.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaders.tsx
  packages/grid/_modules_/grid/components/editCell/EditInputCell.tsx
  packages/grid/_modules_/grid/components/index.ts
  packages/grid/_modules_/grid/constants/eventsConstants.ts
  packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts
  packages/grid/_modules_/grid/hooks/features/rows/index.ts
  packages/grid/_modules_/grid/hooks/features/rows/useGridEditRows.ts
  packages/grid/_modules_/grid/hooks/features/rows/useGridParamsApi.ts
  packages/grid/_modules_/grid/hooks/features/sorting/useGridSorting.ts
  packages/grid/_modules_/grid/hooks/root/useEvents.ts
  packages/grid/_modules_/grid/hooks/root/useGridApiEventHandler.ts
  packages/grid/_modules_/grid/hooks/root/useGridApiMethod.ts
  packages/grid/_modules_/grid/models/api/gridApi.ts
  packages/grid/_modules_/grid/models/api/gridEditRowApi.ts
  packages/grid/_modules_/grid/models/api/gridParamsApi.ts
  packages/grid/_modules_/grid/models/api/index.ts
  packages/grid/_modules_/grid/models/colDef/gridColDef.ts
  packages/grid/_modules_/grid/models/gridOptions.tsx
  packages/grid/_modules_/grid/models/params/gridCellParams.ts
  packages/grid/_modules_/grid/models/params/gridColParams.ts
  packages/grid/_modules_/grid/models/params/gridRowParams.ts
  packages/grid/_modules_/grid/utils/domUtils.ts
  packages/grid/_modules_/grid/utils/index.ts
  packages/grid/_modules_/grid/utils/paramsUtils.ts
  packages/grid/data-grid/src/tests/layout.DataGrid.test.tsx
  packages/grid/x-grid/src/tests/events.XGrid.test.tsx
  packages/storybook/.storybook/preview.tsx
  packages/storybook/src/stories/grid-columns.stories.tsx
  packages/storybook/src/stories/grid-events.stories.tsx
  packages/storybook/src/stories/playground/RecipeReviewCard.tsx
  packages/storybook/src/stories/playground/customComponents.tsx
  packages/storybook/src/stories/playground/customize-components.stories.tsx
  packages/storybook/src/stories/playground/data-grid.options.stories.tsx
  packages/storybook/src/stories/playground/options.stories.tsx
  packages/storybook/src/stories/playground/real-data-demo.stories.tsx
Labels: breaking change, bug 🐛, component: DataGrid

#1209 [core] Batch small changes
  .gitattributes
  netlify.toml
  packages/grid/x-grid-data-generator/some.json
Labels: core

#1210 [docs] Reinforce that columns are definitions
  docs/src/pages/components/data-grid/columns/columns.md
Labels: component: DataGrid, docs

#1237 [docs] Fix linking to sorting component in data-grid overview page
  docs/src/pages/components/data-grid/overview/overview.md
Labels: docs

#1199 [DataGrid] Add onScrollBottom to support infinite loading
  docs/pages/api-docs/x-grid.md
  docs/src/pages/components/data-grid/rows/InfiniteLoadingGrid.js
  docs/src/pages/components/data-grid/rows/InfiniteLoadingGrid.tsx
  docs/src/pages/components/data-grid/rows/rows.md
  packages/grid/_modules_/grid/GridComponent.tsx
  packages/grid/_modules_/grid/components/GridScrollArea.tsx
  packages/grid/_modules_/grid/components/GridViewport.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaders.tsx
  packages/grid/_modules_/grid/constants/eventsConstants.ts
  packages/grid/_modules_/grid/hooks/features/infiniteLoader/index.ts
  packages/grid/_modules_/grid/hooks/features/infiniteLoader/useGridInfiniteLoader.ts
  packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboard.ts
  packages/grid/_modules_/grid/hooks/features/pagination/useGridPagination.ts
  packages/grid/_modules_/grid/hooks/features/virtualization/renderingStateSelector.ts
  packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts
  packages/grid/_modules_/grid/hooks/root/gridContainerSizesSelector.ts
  packages/grid/_modules_/grid/models/api/gridVirtualizationApi.ts
  packages/grid/_modules_/grid/models/gridOptions.tsx
  packages/grid/_modules_/grid/models/params/gridRowScrollEndParams.ts
  packages/grid/_modules_/grid/models/params/index.ts
  packages/grid/data-grid/src/DataGrid.tsx
  packages/grid/x-grid/src/tests/apiRef.XGrid.test.tsx
  packages/storybook/src/stories/grid-rendering.stories.tsx
Labels: component: DataGrid, enhancement

#1205 [DataGrid] Edit Cell Navigation
  packages/grid/_modules_/grid/GridComponent.tsx
  packages/grid/_modules_/grid/components/GridViewport.tsx
  packages/grid/_modules_/grid/components/cell/GridCell.tsx
  packages/grid/_modules_/grid/components/cell/GridEditInputCell.tsx
  packages/grid/_modules_/grid/components/cell/GridEmptyCell.tsx
  packages/grid/_modules_/grid/components/cell/GridRowCells.tsx
  packages/grid/_modules_/grid/components/cell/index.ts
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaders.tsx
  packages/grid/_modules_/grid/components/index.ts
  packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnMenu.tsx
  packages/grid/_modules_/grid/components/panel/GridPanel.tsx
  packages/grid/_modules_/grid/components/toolbar/GridDensitySelector.tsx
  packages/grid/_modules_/grid/components/toolbar/GridToolbarExport.tsx
  packages/grid/_modules_/grid/constants/eventsConstants.ts
  packages/grid/_modules_/grid/hooks/features/core/useGridState.ts
  packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboard.ts
  packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboardNavigation.ts
  packages/grid/_modules_/grid/hooks/features/rows/useGridEditRows.ts
  packages/grid/_modules_/grid/hooks/features/rows/useGridParamsApi.ts
  packages/grid/_modules_/grid/models/api/gridApi.ts
  packages/grid/_modules_/grid/models/api/gridEditRowApi.ts
  packages/grid/_modules_/grid/models/api/gridNavigationApi.ts
  packages/grid/_modules_/grid/models/colDef/gridStringColDef.ts
  packages/grid/_modules_/grid/models/gridEditRowModel.ts
  packages/grid/_modules_/grid/models/gridOptions.tsx
  packages/grid/_modules_/grid/models/params/gridCellParams.ts
  packages/grid/_modules_/grid/models/params/gridEditCellParams.ts
  packages/grid/_modules_/grid/utils/keyboardUtils.ts
  packages/grid/x-grid/src/tests/apiRef.XGrid.test.tsx
  packages/grid/x-grid/src/tests/editRows.XGrid.test.tsx
  packages/grid/x-grid/src/tests/events.XGrid.test.tsx
  packages/grid/x-grid/src/tests/export.XGrid.test.tsx
  packages/grid/x-grid/src/tests/rows.XGrid.test.tsx
  packages/storybook/.storybook/preview.tsx
  packages/storybook/src/stories/grid-rows.stories.tsx
  packages/storybook/src/stories/playground/real-data-demo.stories.tsx
Labels: component: DataGrid, enhancement

#1240 [DataGrid] Fix Popper z-index
  packages/grid/_modules_/grid/components/menu/GridMenu.tsx
  packages/grid/_modules_/grid/components/panel/GridPanel.tsx
Labels: bug 🐛, component: DataGrid

#1257 [core] No top-level imports
  packages/grid/_modules_/grid/components/panel/GridPanelWrapper.tsx
  packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterForm.tsx
Labels: core, performance

#1259 [core] Remove dead code
  packages/grid/_modules_/grid/models/api/gridLocaleTextApi.ts
  packages/grid/_modules_/grid/utils/utils.ts
Labels: core

#1284 [DataGrid] Fix page shift after toggling column
  packages/grid/_modules_/grid/components/panel/GridPanelWrapper.tsx
  packages/grid/data-grid/src/tests/toolbar.DataGrid.test.tsx
Labels: bug 🐛, component: DataGrid

#1279 [DataGrid] Fix loader flag from useDemoData hook
  packages/grid/x-grid-data-generator/src/useDemoData.ts
Labels: bug 🐛, docs

#1253 [DataGrid] Fix render
  packages/grid/_modules_/grid/components/GridRenderingZone.tsx
  packages/grid/_modules_/grid/components/GridStickyContainer.tsx
  packages/grid/_modules_/grid/components/GridViewport.tsx
  packages/grid/_modules_/grid/components/cell/GridCell.tsx
  packages/grid/_modules_/grid/components/cell/GridRowCells.tsx
  packages/grid/_modules_/grid/components/containers/GridDataContainer.tsx
  packages/grid/_modules_/grid/components/containers/GridWindow.tsx
  packages/grid/_modules_/grid/constants/eventsConstants.ts
  packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboardNavigation.ts
  packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts
  packages/grid/_modules_/grid/hooks/root/gridContainerSizesSelector.ts
  packages/grid/_modules_/grid/hooks/root/useGridContainerProps.ts
  packages/grid/_modules_/grid/models/gridContainerProps.ts
  packages/grid/_modules_/grid/utils/getTotalHeight.ts
  packages/grid/data-grid/src/tests/keyboard.DataGrid.test.tsx
  packages/grid/x-grid/src/tests/rows.XGrid.test.tsx
  packages/storybook/src/stories/grid-data.stories.tsx
  packages/storybook/src/stories/grid-toolbar.stories.tsx
  packages/storybook/src/style/grid-stories.css
Labels: bug 🐛, component: DataGrid

#1310 [core] Batch small changes
  docs/next.config.js
  docs/package.json
  docs/src/pages/components/data-grid/rendering/rendering.md
  packages/grid/data-grid/src/tests/rows.DataGrid.test.tsx
  packages/grid/x-grid/src/tests/events.XGrid.test.tsx
  packages/grid/x-grid/src/tests/rows.XGrid.test.tsx
Labels: core, umbrella

#1252 [DataGrid] Forward grid slot components props
  docs/pages/api-docs/data-grid.md
  docs/pages/api-docs/x-grid.md
  docs/src/pages/components/data-grid/rendering/AntDesignGrid.js
  docs/src/pages/components/data-grid/rendering/AntDesignGrid.tsx
  docs/src/pages/components/data-grid/rendering/CustomPaginationGrid.js
  docs/src/pages/components/data-grid/rendering/CustomPaginationGrid.tsx
  packages/grid/_modules_/grid/GridComponent.tsx
  packages/grid/_modules_/grid/components/ErrorOverlay.tsx
  packages/grid/_modules_/grid/components/GridFooter.tsx
  packages/grid/_modules_/grid/components/GridHeader.tsx
  packages/grid/_modules_/grid/components/GridLoadingOverlay.tsx
  packages/grid/_modules_/grid/components/GridNoRowsOverlay.tsx
  packages/grid/_modules_/grid/components/GridPagination.tsx
  packages/grid/_modules_/grid/components/containers/GridFooterContainer.tsx
  packages/grid/_modules_/grid/components/containers/GridOverlay.tsx
  packages/grid/_modules_/grid/components/containers/GridToolbarContainer.tsx
  packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnMenu.tsx
  packages/grid/_modules_/grid/components/panel/GridPanel.tsx
  packages/grid/_modules_/grid/components/panel/GridPreferencesPanel.tsx
  packages/grid/_modules_/grid/components/toolbar/GridToolbar.tsx
  packages/grid/_modules_/grid/hooks/features/index.ts
  packages/grid/_modules_/grid/hooks/features/useGridSlotComponentProps.tsx
  packages/grid/_modules_/grid/models/gridSlotsComponent.ts
  packages/grid/_modules_/grid/models/params/gridSlotComponentProps.ts
  packages/grid/_modules_/grid/models/params/index.ts
  packages/storybook/src/stories/playground/customComponents.tsx
  packages/storybook/src/stories/playground/customize-components.stories.tsx
Labels: breaking change, bug 🐛, component: DataGrid

#1292 [DataGrid] Rename missed modules
  docs/src/pages/components/data-grid/filtering/BasicToolbarFilteringGrid.tsx
  docs/src/pages/components/data-grid/filtering/CustomRatingOperator.tsx
  docs/src/pages/components/data-grid/filtering/ExtendNumericOperator.tsx
  docs/src/pages/components/data-grid/filtering/MultiFilteringWithOrGrid.tsx
  docs/src/pages/components/data-grid/filtering/filtering.md
  packages/grid/_modules_/grid/components/GridRow.tsx
  packages/grid/_modules_/grid/components/GridViewport.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderSortIcon.tsx
  packages/grid/_modules_/grid/components/menu/GridMenu.tsx
  packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnHeaderMenu.tsx
  packages/grid/_modules_/grid/components/menu/columnMenu/GridColumnsMenuItem.tsx
  packages/grid/_modules_/grid/components/menu/columnMenu/GridFilterItemProps.tsx
  packages/grid/_modules_/grid/components/menu/columnMenu/GridFilterMenuItem.tsx
  packages/grid/_modules_/grid/components/menu/columnMenu/HideGridColMenuItem.tsx
  packages/grid/_modules_/grid/components/menu/columnMenu/SortGridMenuItems.tsx
  packages/grid/_modules_/grid/components/menu/columnMenu/index.ts
  packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterForm.tsx
  packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterInputValue.tsx
  packages/grid/_modules_/grid/components/panel/filterPanel/GridFilterInputValueProps.ts
  packages/grid/_modules_/grid/components/panel/filterPanel/index.ts
  packages/grid/_modules_/grid/hooks/features/columnMenu/columnMenuState.ts
  packages/grid/_modules_/grid/hooks/features/columnReorder/columnReorderSelector.ts
  packages/grid/_modules_/grid/hooks/features/columnReorder/columnReorderState.ts
  packages/grid/_modules_/grid/hooks/features/core/gridState.ts
  packages/grid/_modules_/grid/hooks/features/filter/gridFilterModelState.ts
  packages/grid/_modules_/grid/hooks/features/filter/gridFilterSelector.ts
  packages/grid/_modules_/grid/hooks/features/filter/index.ts
  packages/grid/_modules_/grid/hooks/features/filter/useGridFilter.ts
  packages/grid/_modules_/grid/hooks/features/keyboard/gridKeyboardSelector.ts
  packages/grid/_modules_/grid/hooks/features/keyboard/gridKeyboardState.ts
  packages/grid/_modules_/grid/hooks/features/keyboard/index.ts
  packages/grid/_modules_/grid/hooks/features/keyboard/keyboardSelector.ts
  packages/grid/_modules_/grid/hooks/features/keyboard/useGridKeyboard.ts
  packages/grid/_modules_/grid/hooks/features/pagination/gridPaginationReducer.ts
  packages/grid/_modules_/grid/hooks/features/pagination/gridPaginationSelector.ts
  packages/grid/_modules_/grid/hooks/features/pagination/useGridPagination.ts
  packages/grid/_modules_/grid/hooks/features/selection/useGridSelection.ts
  packages/grid/_modules_/grid/hooks/features/virtualization/useGridVirtualRows.ts
  packages/grid/_modules_/grid/hooks/root/useGridContainerProps.ts
  packages/grid/_modules_/grid/models/api/filterApi.ts
  packages/grid/_modules_/grid/models/api/gridApi.ts
  packages/grid/_modules_/grid/models/api/gridComponentsApi.ts
  packages/grid/_modules_/grid/models/api/gridLocaleTextApi.ts
  packages/grid/_modules_/grid/models/gridFilterOperator.ts
  packages/grid/_modules_/grid/models/gridOptions.tsx
  packages/grid/_modules_/grid/models/gridRows.ts
  packages/grid/_modules_/grid/models/params/gridFilterModelParams.ts
  packages/grid/x-grid/src/tests/filtering.XGrid.test.tsx
  packages/storybook/src/stories/grid-filter.stories.tsx
Labels: breaking change, component: DataGrid

#1299 [DataGrid] Refactor useGridColumnReorder
  docs/pages/api-docs/data-grid.md
  docs/pages/api-docs/x-grid.md
  docs/src/pages/components/data-grid/columns/columns.md
  docs/src/pages/components/data-grid/rendering/rendering.md
  packages/grid/_modules_/grid/components/GridCheckboxRenderer.tsx
  packages/grid/_modules_/grid/components/GridScrollArea.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaderItem.tsx
  packages/grid/_modules_/grid/components/columnHeaders/GridColumnHeaders.tsx
  packages/grid/_modules_/grid/constants/eventsConstants.ts
  packages/grid/_modules_/grid/hooks/features/columnReorder/useGridColumnReorder.tsx
  packages/grid/_modules_/grid/hooks/features/columns/useGridColumns.ts
  packages/grid/_modules_/grid/hooks/features/rows/useGridParamsApi.ts
  packages/grid/_modules_/grid/hooks/features/sorting/useGridSorting.ts
  packages/grid/_modules_/grid/hooks/features/useGridColumnResize.tsx
  packages/grid/_modules_/grid/hooks/root/useEvents.ts
  packages/grid/_modules_/grid/models/api/columnReorderApi.ts
  packages/grid/_modules_/grid/models/api/gridApi.ts
  packages/grid/_modules_/grid/models/api/gridColumnApi.ts
  packages/grid/_modules_/grid/models/api/gridParamsApi.ts
  packages/grid/_modules_/grid/models/colDef/gridColDef.ts
  packages/grid/_modules_/grid/models/cursorCoordinates.ts
  packages/grid/_modules_/grid/models/gridOptions.tsx
  packages/grid/_modules_/grid/models/index.ts
  packages/grid/_modules_/grid/models/params/gridColumnHeaderParams.ts
  packages/grid/_modules_/grid/models/params/gridColumnOrderChangeParams.ts
  packages/grid/_modules_/grid/models/params/index.ts
  packages/grid/x-grid/src/tests/events.XGrid.test.tsx
  packages/grid/x-grid/src/tests/reorder.XGrid.test.tsx
Labels: breaking change
